# Generated by Django 4.2.9 on 2026-04-29 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_initial'),
        ('finance', '0002_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('spent_to_date', models.DecimalField(decimal_places=2, max_digits=12)),
                ('days_observed', models.PositiveIntegerField(default=0)),
                ('daily_burn_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('weekly_burn_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('projected_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('projected_overrun', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_to_exhaustion', models.IntegerField(blank=True, help_text='Days until allocation is exhausted at current burn. Null if burn<=0.', null=True)),
                ('exhaustion_date', models.DateField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forecast', to='finance.budgetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('FORECAST_OVERRUN', 'Forecast Budget Overrun'), ('BURN_TOO_FAST', 'Burn Rate Too Fast'), ('RATE_SPIKE', 'Supplier Rate Spike'), ('LOW_STOCK_PROJECTION', 'Projected Low Stock')], max_length=30)),
                ('scope_key', models.CharField(help_text='e.g. category:42 or supplier:3/material:8', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='WARNING', max_length=10)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('alert_type', 'scope_key')},
            },
        ),
        migrations.CreateModel(
            name='SupplierRateTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_seen_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_rate_30d', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_rate_90d', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_pct_last_month', models.FloatField(default=0.0, help_text='% change comparing the latest 30-day avg vs the prior 30 days.')),
                ('transactions_count', models.PositiveIntegerField(default=0)),
                ('window_end', models.DateField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_trends', to='resources.material')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_trends', to='accounting.vendor')),
            ],
            options={
                'ordering': ['-change_pct_last_month'],
                'unique_together': {('supplier', 'material')},
            },
        ),
    ]
