# Generated by Django 4.2.9 on 2026-05-15 05:04
# Fixed: PostgreSQL cannot cast bigint → uuid via ALTER COLUMN … USING.
# Strategy: truncate stale rows (all existing material_id values pointed at the
# now-removed resources.Material integer table — none are valid any more),
# drop the old column, re-add as a fresh uuid FK.
# unique_together (supplier, material) index is recreated manually.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_stockmovement_delivered_by_and_more'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        # All existing rows reference the old resources.Material integer table.
        # They cannot be remapped — clear them so the column can be recreated.
        migrations.RunSQL(
            sql='TRUNCATE TABLE analytics_supplierratetrend;',
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Drop old bigint material_id (CASCADE also removes the unique_together index).
        migrations.RunSQL(
            sql='ALTER TABLE analytics_supplierratetrend DROP COLUMN IF EXISTS material_id CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Re-add as uuid FK (NOT NULL — mirrors original field definition).
        migrations.RunSQL(
            sql="""
                ALTER TABLE analytics_supplierratetrend
                    ADD COLUMN material_id uuid NOT NULL
                    REFERENCES resource_material (id)
                    ON DELETE CASCADE
                    DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql='ALTER TABLE analytics_supplierratetrend DROP COLUMN IF EXISTS material_id CASCADE;',
        ),

        # Recreate the unique_together (supplier_id, material_id) index.
        migrations.RunSQL(
            sql="""
                CREATE UNIQUE INDEX IF NOT EXISTS
                    analytics_supplierratetrend_supplier_id_material_id_uniq
                    ON analytics_supplierratetrend (supplier_id, material_id);
            """,
            reverse_sql='DROP INDEX IF EXISTS analytics_supplierratetrend_supplier_id_material_id_uniq;',
        ),

        # Update Django migration state — no SQL needed (done above).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='supplierratetrend',
                    name='material',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rate_trends',
                        to='resource.material',
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
