# Generated by Django 4.2.9 on 2026-05-28 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0008_equipment_type_choices_fix'),
        ('analytics', '0003_alter_supplierratetrend_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierratetrend',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_trends', to='resource.supplier'),
        ),
    ]
