/**
 * LoanForm — create or edit a loan account.
 * Also handles disbursement (first deposit) into a target bank account.
 */
import { useState, useEffect } from 'react';
import financeApi from '../../services/financeApi';
import { useFinance } from '../../context/FinanceContext';

const inp = 'w-full px-3 py-2 text-sm border border-gray-300 rounded-xl focus:outline-none focus:ring-2 focus:ring-black/10 bg-white';
const lbl = 'block text-[10px] font-bold text-gray-500 uppercase tracking-wider mb-1';

const EMPTY = {
  code: '', name: '', account_type: 'LIABILITY',
  bank_name: '', account_number: '', account_holder_name: '',
  is_bank: false, is_loan: true,
  interest_rate: '', loan_tenure_months: '', emi_amount: '', total_loan_limit: '',
};

function calcEMI(principal, annualRate, months) {
  if (!principal || !months) return 0;
  const r = (annualRate || 0) / 100 / 12;
  const n = months;
  if (r === 0) return principal / n;
  return (principal * r * Math.pow(1 + r, n)) / (Math.pow(1 + r, n) - 1);
}

export default function LoanForm({ account = null, onDone }) {
  const { projectId, banks, refresh } = useFinance();
  const [form, setForm]     = useState(EMPTY);
  const [disburse, setDisburse] = useState(false);
  const [disburseForm, setDisburseForm] = useState({ bank_account_id: '', amount: '', description: '' });
  const [busy, setBusy]     = useState(false);
  const [err,  setErr]      = useState('');

  // UI Helper States
  const [loanCategory, setLoanCategory] = useState('bank'); // 'bank' or 'personal'
  const [hasInterest, setHasInterest]   = useState(true);
  const [hasFixedTerm, setHasFixedTerm] = useState(true);
  const [showAdvanced, setShowAdvanced] = useState(false);

  // Flag to check if name was auto-generated to avoid overwriting user input
  const [isNameAutoGenerated, setIsNameAutoGenerated] = useState(true);

  useEffect(() => {
    if (account) {
      setForm({ ...EMPTY, ...account });
      const isPersonal = !account.account_number && (Number(account.interest_rate) === 0 || !account.bank_name);
      setLoanCategory(isPersonal ? 'personal' : 'bank');
      setHasInterest(Number(account.interest_rate) > 0);
      setHasFixedTerm(Number(account.loan_tenure_months) > 0);
      setIsNameAutoGenerated(account.name === `${account.bank_name} Loan` || account.name === '');
    } else {
      setForm({ ...EMPTY, code: String(Math.floor(2000 + Math.random() * 1000)) });
      setLoanCategory('bank');
      setHasInterest(true);
      setHasFixedTerm(true);
      setIsNameAutoGenerated(true);
    }
  }, [account]);

  const set = (k, v) => setForm((f) => {
    const updated = { ...f, [k]: v };
    // Auto-calculate EMI
    if (['total_loan_limit', 'interest_rate', 'loan_tenure_months'].includes(k)) {
      const emi = calcEMI(
        Number(updated.total_loan_limit),
        Number(updated.interest_rate),
        Number(updated.loan_tenure_months)
      );
      if (emi > 0) updated.emi_amount = emi.toFixed(2);
    }
    return updated;
  });

  const setD = (k, v) => setDisburseForm((f) => ({ ...f, [k]: v }));

  // Helper when user toggles Loan Category
  const handleCategoryChange = (category) => {
    setLoanCategory(category);
    if (category === 'personal') {
      // Default personal loans to interest-free and flexible term for easier flow
      setHasInterest(false);
      setHasFixedTerm(false);
      setForm(f => ({ ...f, interest_rate: '0', loan_tenure_months: '', emi_amount: '' }));
    } else {
      setHasInterest(true);
      setHasFixedTerm(true);
      setForm(f => ({ ...f, interest_rate: '12.00', loan_tenure_months: '60' }));
    }
  };

  // Helper when user toggles Interest Mode
  const handleInterestToggle = (interested) => {
    setHasInterest(interested);
    if (!interested) {
      setForm(f => ({ ...f, interest_rate: '0', emi_amount: calcEMI(Number(f.total_loan_limit), 0, Number(f.loan_tenure_months)).toFixed(2) }));
    } else {
      setForm(f => {
        const rate = '12.00';
        return {
          ...f,
          interest_rate: rate,
          emi_amount: calcEMI(Number(f.total_loan_limit), Number(rate), Number(f.loan_tenure_months)).toFixed(2)
        };
      });
    }
  };

  // Helper when user toggles Tenure Mode
  const handleTenureToggle = (fixed) => {
    setHasFixedTerm(fixed);
    if (!fixed) {
      setForm(f => ({ ...f, loan_tenure_months: '', emi_amount: '' }));
    } else {
      setForm(f => {
        const months = '60';
        return {
          ...f,
          loan_tenure_months: months,
          emi_amount: calcEMI(Number(f.total_loan_limit), Number(f.interest_rate), Number(months)).toFixed(2)
        };
      });
    }
  };

  // Auto-generate Loan Name if borrower or lender details change
  const handleLenderNameChange = (val) => {
    set('bank_name', val);
    if (isNameAutoGenerated) {
      set('name', val ? `${val} Loan` : '');
    }
  };

  const handleDelete = async () => {
    if (!window.confirm(`Are you sure you want to delete "${form.name}"?`)) return;
    setBusy(true); setErr('');
    try {
      await financeApi.deleteAccount(account.id);
      await refresh();
      onDone();
    } catch (ex) {
      const msg = ex?.response?.data?.detail || JSON.stringify(ex?.response?.data) || ex.message;
      if (msg.toLowerCase().includes('protect') || msg.toLowerCase().includes('dependency') || msg.toLowerCase().includes('journal')) {
        if (window.confirm(`Cannot delete loan because it has disbursement or payment transactions. Would you like to deactivate (archive) this loan instead so it doesn't show in the dashboard?`)) {
          try {
            await financeApi.updateAccount(account.id, { ...form, is_active: false });
            await refresh();
            onDone();
          } catch (deactEx) {
            setErr(deactEx?.response?.data?.detail || JSON.stringify(deactEx?.response?.data) || deactEx.message);
          }
        }
      } else {
        setErr(msg);
      }
    } finally {
      setBusy(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setBusy(true); setErr('');
    try {
      const finalForm = { ...form };
      if (!hasInterest) finalForm.interest_rate = '0';
      if (!hasFixedTerm) {
        finalForm.loan_tenure_months = null;
        finalForm.emi_amount = null;
      }

      let loanAccount;
      if (account) {
        await financeApi.updateAccount(account.id, finalForm);
      } else {
        const res = await financeApi.createAccount({ ...finalForm, project: projectId });
        loanAccount = res.data;
      }

      // Optionally disburse
      if (!account && disburse && disburseForm.bank_account_id && disburseForm.amount) {
        await financeApi.createDisbursement({
          loan_account:  loanAccount.id,
          bank_account:  disburseForm.bank_account_id,
          amount:        disburseForm.amount,
          description:   disburseForm.description || `Loan disbursement — ${finalForm.name}`,
          project:       projectId,
        });
      }

      await refresh();
      onDone();
    } catch (ex) {
      setErr(ex?.response?.data?.detail || JSON.stringify(ex?.response?.data) || ex.message);
    } finally {
      setBusy(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="p-6 space-y-4">
      {err && <p className="text-xs text-red-600 font-semibold bg-red-50 p-2 rounded-lg">{err}</p>}

      {/* Category selector */}
      <div className="flex gap-2 p-1 bg-gray-100 rounded-xl">
        <button
          type="button"
          onClick={() => handleCategoryChange('bank')}
          className={`flex-1 py-2 text-xs font-black rounded-lg transition-all flex items-center justify-center gap-1.5 ${
            loanCategory === 'bank'
              ? 'bg-white shadow-sm text-gray-900 border border-gray-200'
              : 'text-gray-500 hover:text-gray-700'
          }`}
        >
          🏦 Bank Loan
        </button>
        <button
          type="button"
          onClick={() => handleCategoryChange('personal')}
          className={`flex-1 py-2 text-xs font-black rounded-lg transition-all flex items-center justify-center gap-1.5 ${
            loanCategory === 'personal'
              ? 'bg-white shadow-sm text-gray-900 border border-gray-200'
              : 'text-gray-500 hover:text-gray-700'
          }`}
        >
          👥 Personal / Friend / Cousin
        </button>
      </div>

      {/* Loan Name */}
      <div>
        <label className={lbl}>Loan Name *</label>
        <input 
          className={inp} 
          required 
          value={form.name} 
          onChange={(e) => {
            set('name', e.target.value);
            setIsNameAutoGenerated(false);
          }} 
          placeholder={loanCategory === 'bank' ? "उदाहरण: एनआईसी एशिया होम लोन" : "उदाहरण: गीता भण्डारी (व्यक्तिगत सापटी)"} 
        />
      </div>

      {/* Lender details */}
      <div className="p-4 bg-blue-50 border border-blue-100 rounded-xl space-y-3">
        <p className="text-[10px] font-black text-blue-600 uppercase tracking-wider">
          {loanCategory === 'bank' ? '🏦 Lender / Bank Details' : '👤 Lender Details'}
        </p>
        
        <div>
          <label className={lbl}>
            {loanCategory === 'bank' ? 'Bank / Lender Name *' : 'Lender Name (Friend / Cousin) *'}
          </label>
          <input 
            className={inp} 
            required
            value={form.bank_name} 
            onChange={(e) => handleLenderNameChange(e.target.value)} 
            placeholder={loanCategory === 'bank' ? "उदाहरण: एनआईसी एशिया बैंक" : "उदाहरण: गीता भण्डारी"} 
          />
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div>
            <label className={lbl}>
              {loanCategory === 'bank' ? 'Loan Account No. *' : 'Account No. / Reference (Optional)'}
            </label>
            <input 
              className={inp} 
              required={loanCategory === 'bank'}
              value={form.account_number} 
              onChange={(e) => set('account_number', e.target.value)} 
              placeholder={loanCategory === 'bank' ? "उदाहरण: ०१२३४५६७८९" : "उदाहरण: ९८५१०XXXXX (वा खाली छाड्नुहोस्)"} 
            />
          </div>
          <div>
            <label className={lbl}>Borrower Name *</label>
            <input 
              className={inp} 
              required
              value={form.account_holder_name} 
              onChange={(e) => set('account_holder_name', e.target.value)} 
              placeholder="उदाहरण: जितेन्द्र खड्का" 
            />
          </div>
        </div>
      </div>

      {/* Loan terms */}
      <div className="p-4 bg-yellow-50 border border-yellow-100 rounded-xl space-y-3">
        <p className="text-[10px] font-black text-yellow-600 uppercase tracking-wider">💰 Loan Terms & Repayment</p>
        
        {/* Toggle options for Personal Loans */}
        {loanCategory === 'personal' && (
          <div className="grid grid-cols-2 gap-3 pb-2 border-b border-yellow-100/50">
            {/* Interest Toggle */}
            <div>
              <label className={lbl}>Interest Type</label>
              <div className="flex bg-white border border-gray-200 rounded-lg p-0.5">
                <button
                  type="button"
                  onClick={() => handleInterestToggle(false)}
                  className={`flex-1 py-1.5 text-[10px] font-black rounded-md transition-all ${!hasInterest ? 'bg-black text-white shadow-sm' : 'text-gray-500 hover:text-gray-700'}`}
                >
                  Interest-Free
                </button>
                <button
                  type="button"
                  onClick={() => handleInterestToggle(true)}
                  className={`flex-1 py-1.5 text-[10px] font-black rounded-md transition-all ${hasInterest ? 'bg-black text-white shadow-sm' : 'text-gray-500 hover:text-gray-700'}`}
                >
                  With Interest
                </button>
              </div>
            </div>

            {/* Tenure Toggle */}
            <div>
              <label className={lbl}>Repayment Term</label>
              <div className="flex bg-white border border-gray-200 rounded-lg p-0.5">
                <button
                  type="button"
                  onClick={() => handleTenureToggle(false)}
                  className={`flex-1 py-1.5 text-[10px] font-black rounded-md transition-all ${!hasFixedTerm ? 'bg-black text-white shadow-sm' : 'text-gray-500 hover:text-gray-700'}`}
                >
                  Flexible / Sapati
                </button>
                <button
                  type="button"
                  onClick={() => handleTenureToggle(true)}
                  className={`flex-1 py-1.5 text-[10px] font-black rounded-md transition-all ${hasFixedTerm ? 'bg-black text-white shadow-sm' : 'text-gray-500 hover:text-gray-700'}`}
                >
                  Fixed Term
                </button>
              </div>
            </div>
          </div>
        )}

        <div className="grid grid-cols-3 gap-3">
          <div>
            <label className={lbl}>Loan Amount (NPR) *</label>
            <input type="number" min="0" step="1" required className={inp} value={form.total_loan_limit} onChange={(e) => set('total_loan_limit', e.target.value)} placeholder="1000000" />
          </div>
          <div>
            <label className={lbl}>Interest Rate % / yr</label>
            <input 
              type="number" 
              min="0" 
              step="0.01" 
              disabled={!hasInterest}
              className={`${inp} ${!hasInterest ? 'bg-gray-100 text-gray-400 cursor-not-allowed border-gray-200' : ''}`}
              value={hasInterest ? form.interest_rate : '0'} 
              onChange={(e) => set('interest_rate', e.target.value)} 
              placeholder="12.00" 
            />
          </div>
          <div>
            <label className={lbl}>Tenure (months)</label>
            <input 
              type="number" 
              min="1" 
              step="1" 
              disabled={!hasFixedTerm}
              required={hasFixedTerm}
              className={`${inp} ${!hasFixedTerm ? 'bg-gray-100 text-gray-400 cursor-not-allowed border-gray-200' : ''}`}
              value={hasFixedTerm ? form.loan_tenure_months : ''} 
              onChange={(e) => set('loan_tenure_months', e.target.value)} 
              placeholder="60" 
            />
          </div>
        </div>

        {hasFixedTerm && (
          <div>
            <label className={lbl}>Monthly EMI (auto-calculated)</label>
            <input type="number" step="0.01" className={inp} value={form.emi_amount} onChange={(e) => set('emi_amount', e.target.value)} placeholder="Auto" />
          </div>
        )}
      </div>

      {/* Advanced section */}
      <div className="border border-gray-200 rounded-xl overflow-hidden">
        <button
          type="button"
          onClick={() => setShowAdvanced(!showAdvanced)}
          className="w-full px-4 py-2.5 bg-gray-50 hover:bg-gray-100 text-left text-xs font-black text-gray-600 flex justify-between items-center transition-colors font-mono"
        >
          <span>⚙️ Bookkeeping Settings (खाता कोड)</span>
          <span className="transition-transform duration-200" style={{ transform: showAdvanced ? 'rotate(90deg)' : 'rotate(0deg)' }}>▶</span>
        </button>
        {showAdvanced && (
          <div className="p-4 border-t border-gray-200 bg-white grid grid-cols-2 gap-3">
            <div>
              <label className={lbl}>Account Code</label>
              <input className={inp} required value={form.code} onChange={(e) => set('code', e.target.value)} placeholder="2001" />
            </div>
            <div>
              <label className={lbl}>Account Type</label>
              <select className={inp} value={form.account_type} onChange={(e) => set('account_type', e.target.value)}>
                <option value="LIABILITY">LIABILITY</option>
                <option value="ASSET">ASSET</option>
              </select>
            </div>
          </div>
        )}
      </div>

      {/* Disbursement (new only) */}
      {!account && (
        <div className="p-4 bg-green-50 border border-green-100 rounded-xl space-y-3">
          <div className="flex items-center justify-between">
            <p className="text-[10px] font-black text-green-600 uppercase">Disburse to Bank Account?</p>
            <input type="checkbox" checked={disburse} onChange={(e) => setDisburse(e.target.checked)} className="w-4 h-4 accent-green-600" />
          </div>
          {disburse && (
            <>
              <div>
                <label className={lbl}>Target Bank Account</label>
                <select className={inp} value={disburseForm.bank_account_id} onChange={(e) => setD('bank_account_id', e.target.value)} required={disburse}>
                  <option value="">— Select bank —</option>
                  {banks.map((b) => (
                    <option key={b.id} value={b.id}>{b.name}</option>
                  ))}
                </select>
              </div>
              <div>
                <label className={lbl}>Disbursement Amount (NPR)</label>
                <input type="number" min="0" step="0.01" className={inp} value={disburseForm.amount}
                  onChange={(e) => setD('amount', e.target.value)} placeholder={form.total_loan_limit || '0.00'} />
              </div>
              <div>
                <label className={lbl}>Description</label>
                <input className={inp} value={disburseForm.description} onChange={(e) => setD('description', e.target.value)} placeholder="Loan disbursement" />
              </div>
            </>
          )}
        </div>
      )}

      <div className="flex gap-2">
        {account && (
          <button type="button" disabled={busy} onClick={handleDelete}
            className="flex-1 py-2.5 border border-red-200 text-red-600 text-sm font-black rounded-xl hover:bg-red-50 disabled:opacity-50 transition-colors">
            🗑 Delete Loan
          </button>
        )}
        <button type="submit" disabled={busy}
          className="flex-1 py-2.5 bg-black text-white text-sm font-black rounded-xl hover:bg-gray-800 disabled:opacity-50 transition-colors">
          {busy ? 'Saving…' : account ? 'Update Loan' : 'Create Loan'}
        </button>
      </div>
    </form>
  );
}
