# Generated by Django 4.2.9 on 2026-04-29 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_transcript', models.TextField()),
                ('language', models.CharField(default='ne', help_text="'ne' / 'en'", max_length=10)),
                ('intent', models.CharField(choices=[('STOCK_CHECK', 'Stock Check'), ('BUDGET_CHECK', 'Budget Check'), ('TASK_ADD', 'Add Task'), ('TASK_COMPLETE', 'Complete Task'), ('EXPENSE_ADD', 'Log Expense'), ('NEXT_STEP', 'What to Do Next'), ('HELP', 'Help'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('parsed_entities', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('response_text', models.TextField(blank=True)),
                ('executed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voice-clips/')),
                ('stt_backend', models.CharField(choices=[('browser', 'Browser SpeechRecognition'), ('whisper', 'OpenAI Whisper'), ('google', 'Google Speech-to-Text'), ('manual', 'Typed fallback')], default='browser', max_length=20)),
                ('duration_sec', models.FloatField(default=0.0)),
                ('retained', models.BooleanField(default=False, help_text='Kept for fine-tuning?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='assistant.voicecommand')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnownPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(db_index=True, max_length=200)),
                ('language', models.CharField(default='ne', max_length=10)),
                ('intent', models.CharField(choices=[('STOCK_CHECK', 'Stock Check'), ('BUDGET_CHECK', 'Budget Check'), ('TASK_ADD', 'Add Task'), ('TASK_COMPLETE', 'Complete Task'), ('EXPENSE_ADD', 'Log Expense'), ('NEXT_STEP', 'What to Do Next'), ('HELP', 'Help'), ('UNKNOWN', 'Unknown')], max_length=30)),
                ('weight', models.FloatField(default=1.0)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['intent', 'phrase'],
                'unique_together': {('phrase', 'intent')},
            },
        ),
    ]
