# Generated by Django 4.2.9 on 2026-05-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin', '0003_installment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentpayment',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='fin/contractor_payments/'),
        ),
    ]
