# Generated by Django 4.2.9 on 2026-04-29 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0001_initial'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('trade', models.CharField(choices=[('MASON', 'Mason (Dakarmi)'), ('HELPER', 'Helper (Jugi)'), ('CARPENTER', 'Carpenter (Mistri)'), ('ELECTRICIAN', 'Electrician'), ('PLUMBER', 'Plumber'), ('PAINTER', 'Painter'), ('STEEL_FIXER', 'Steel Fixer (Lohari)'), ('SUPERVISOR', 'Site Supervisor'), ('TILE_SETTER', 'Tile Setter'), ('EXCAVATOR', 'Excavator Operator'), ('WATERPROOF', 'Waterproofing Applicator'), ('DRIVER', 'Driver'), ('SECURITY', 'Security Guard'), ('ENGINEER', 'Engineer'), ('ACCOUNTANT', 'Accountant'), ('MANAGER', 'Project Manager'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('worker_type', models.CharField(choices=[('LABOUR', 'Daily Labour'), ('STAFF', 'Salaried Staff')], default='LABOUR', max_length=10)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, help_text='Daily wage rate in NPR', max_digits=10)),
                ('overtime_rate_per_hour', models.DecimalField(decimal_places=2, default=0, help_text='Overtime rate per hour in NPR (0 = auto 1.5x daily/8h)', max_digits=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('use_custom_window', models.BooleanField(default=False, help_text='Enable a custom scan time window for this worker (overrides project window)')),
                ('custom_checkin_start', models.TimeField(blank=True, help_text='HH:MM — custom check-in window opens', null=True)),
                ('custom_checkin_end', models.TimeField(blank=True, help_text='HH:MM — custom check-in window closes', null=True)),
                ('custom_checkout_start', models.TimeField(blank=True, help_text='HH:MM — custom check-out window opens', null=True)),
                ('custom_checkout_end', models.TimeField(blank=True, help_text='HH:MM — custom check-out window closes', null=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique token embedded in QR badge. Scan to mark check-in/out.', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.OneToOneField(blank=True, help_text='Linked resource/contractor record for this attendance worker', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_worker', to='resources.contractor')),
                ('linked_user', models.ForeignKey(blank=True, help_text='Link to system user account (for staff)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_worker_profile', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_workers', to='core.houseproject')),
                ('project_member', models.OneToOneField(blank=True, help_text='Link to project team member (if this worker is also a team member)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_worker', to='core.projectmember')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LEAVE', 'Leave'), ('HOLIDAY', 'Holiday')], default='PRESENT', max_length=10)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('daily_rate_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_rate_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to='core.houseproject')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records_created', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.attendanceworker')),
            ],
            options={
                'ordering': ['-date', 'worker__name'],
                'unique_together': {('worker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ScanTimeWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_start', models.TimeField(default='08:00', help_text='Check-in window opens (HH:MM)')),
                ('checkin_end', models.TimeField(default='10:00', help_text='Check-in window closes (HH:MM)')),
                ('checkout_start', models.TimeField(default='17:00', help_text='Check-out window opens (HH:MM)')),
                ('checkout_end', models.TimeField(default='19:00', help_text='Check-out window closes (HH:MM)')),
                ('is_active', models.BooleanField(default=False, help_text='When True, scans outside configured windows are rejected.')),
                ('late_threshold_minutes', models.PositiveIntegerField(default=30, help_text='Minutes after checkin_start before a scan is marked LATE')),
                ('early_checkout_minutes', models.PositiveIntegerField(default=30, help_text='Minutes before checkout_start before a scan is marked EARLY')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_windows_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_time_window', to='core.houseproject')),
            ],
            options={
                'verbose_name': 'Scan Time Window',
            },
        ),
        migrations.CreateModel(
            name='QRScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('IGNORED', 'Duplicate — ignored (cooldown)'), ('OUT_OF_TIME', 'Out of time window — not registered'), ('BLOCKED', 'Blocked — wrong action for current state'), ('INVALID', 'Invalid QR code')], max_length=15)),
                ('scan_status', models.CharField(choices=[('VALID', 'Valid — registered'), ('REJECTED', 'Rejected — not registered'), ('DUPLICATE', 'Duplicate — cooldown active')], default='VALID', max_length=10)),
                ('is_late', models.BooleanField(default=False, help_text='Check-in was after late threshold')),
                ('is_early', models.BooleanField(default=False, help_text='Check-out was before early threshold')),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='attendance.dailyattendance')),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans_performed', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scan_logs', to='attendance.attendanceworker')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.TimeField(default='08:00', help_text='Standard shift start time')),
                ('shift_end', models.TimeField(default='17:00', help_text='Standard shift end time')),
                ('break_minutes', models.PositiveIntegerField(default=60, help_text='Unpaid break duration in minutes (deducted from worked hours)')),
                ('working_hours_per_day', models.DecimalField(decimal_places=1, default=8, help_text='Standard working hours per day. Hours worked beyond this count as overtime.', max_digits=4)),
                ('auto_overtime', models.BooleanField(default=True, help_text='Auto-calculate overtime from check-in/out times when saving attendance')),
                ('weekly_off_days', models.CharField(default='6', help_text='Comma-separated day numbers: 0=Mon … 6=Sun', max_length=20)),
                ('auto_mark_weekend_off', models.BooleanField(default=False, help_text='Auto-mark all workers as HOLIDAY on weekly off days when sheet is loaded')),
                ('auto_apply_holiday', models.BooleanField(default=True, help_text='When a ProjectHoliday is saved, auto-mark all workers as HOLIDAY for that date')),
                ('annual_leave_days', models.PositiveIntegerField(default=12, help_text='Paid annual leave days per year')),
                ('sick_leave_days', models.PositiveIntegerField(default=6, help_text='Paid sick leave days per year')),
                ('leave_carry_forward', models.BooleanField(default=False, help_text='Allow unused annual leave to carry forward to next year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='core.houseproject')),
            ],
            options={
                'verbose_name': 'Attendance Settings',
            },
        ),
        migrations.CreateModel(
            name='ProjectHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(help_text='e.g. Dashain, Tihar, Workers Day', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('applied', models.BooleanField(default=False, help_text="True once the holiday has been applied to all workers' attendance")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='core.houseproject')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('project', 'date')},
            },
        ),
    ]
