# Generated by Django 4.2.9 on 2026-05-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceworker',
            name='nfc_uid',
            field=models.CharField(blank=True, help_text='Hardware UID of the assigned NFC card/fob (e.g., 01010112D919C800)', max_length=50, null=True, unique=True),
        ),
    ]
