# Generated by Django 4.2.9 on 2026-05-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendanceworker_nfc_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattendancesettings',
            name='mqtt_broker_url',
            field=models.CharField(default='localhost', help_text='IP or URL of the MQTT Broker', max_length=255),
        ),
        migrations.AddField(
            model_name='projectattendancesettings',
            name='mqtt_port',
            field=models.PositiveIntegerField(default=1883, help_text='Port of the MQTT Broker'),
        ),
    ]
