# Generated by Django 4.2.9 on 2026-05-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_projectattendancesettings_mqtt_broker_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattendancesettings',
            name='mqtt_topic',
            field=models.CharField(default='nfc/+/state', help_text='MQTT Topic to subscribe to. Use + as wildcard for MAC address.', max_length=255),
        ),
    ]
