# Generated by Django 4.2.9 on 2026-05-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_projectattendancesettings_mqtt_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattendancesettings',
            name='mqtt_password',
            field=models.CharField(blank=True, default='', help_text='MQTT broker password (leave blank for anonymous)', max_length=255),
        ),
        migrations.AddField(
            model_name='projectattendancesettings',
            name='mqtt_username',
            field=models.CharField(blank=True, default='', help_text='MQTT broker username (leave blank for anonymous)', max_length=255),
        ),
    ]
