# Generated by Django 4.2.9 on 2026-05-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_mqtt_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattendancesettings',
            name='timezone',
            field=models.CharField(default='Asia/Kathmandu', help_text='Timezone for this project (e.g., Asia/Kathmandu, Asia/Kolkata, UTC)', max_length=50),
        ),
    ]
