# Generated by Django 4.2.9 on 2026-05-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_projectattendancesettings_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattendancesettings',
            name='sound_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable chime sounds on scan success/error'),
        ),
        migrations.AddField(
            model_name='projectattendancesettings',
            name='sound_theme',
            field=models.CharField(default='harmonic', help_text='Sound theme: harmonic, classic, or modern', max_length=50),
        ),
        migrations.AddField(
            model_name='projectattendancesettings',
            name='sound_volume',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Master volume for chime sounds (0.0 to 1.0)', max_digits=3),
        ),
        migrations.AddField(
            model_name='projectattendancesettings',
            name='voice_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable voice announcements of staff names'),
        ),
        migrations.AddField(
            model_name='projectattendancesettings',
            name='voice_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Speech rate for voice announcements (0.5 to 2.0)', max_digits=3),
        ),
    ]
