# Generated by Django 4.2.9 on 2026-04-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_project_holiday_applied_and_attendance_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectattendancesettings',
            name='auto_apply_holiday',
            field=models.BooleanField(default=True, help_text='When a ProjectHoliday is saved, auto-mark all workers as HOLIDAY for that date'),
        ),
        migrations.AlterField(
            model_name='projectattendancesettings',
            name='auto_mark_weekend_off',
            field=models.BooleanField(default=False, help_text='Auto-mark all workers as HOLIDAY on weekly off days when sheet is loaded'),
        ),
        migrations.AlterField(
            model_name='projectattendancesettings',
            name='auto_overtime',
            field=models.BooleanField(default=True, help_text='Auto-calculate overtime from check-in/out times when saving attendance'),
        ),
        migrations.AlterField(
            model_name='projectattendancesettings',
            name='break_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Unpaid break duration in minutes (deducted from worked hours)'),
        ),
        migrations.AlterField(
            model_name='projectattendancesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectattendancesettings',
            name='leave_carry_forward',
            field=models.BooleanField(default=False, help_text='Allow unused annual leave to carry forward to next year'),
        ),
        migrations.AlterField(
            model_name='projectattendancesettings',
            name='weekly_off_days',
            field=models.CharField(default='6', help_text='Comma-separated day numbers: 0=Mon … 6=Sun', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectattendancesettings',
            name='working_hours_per_day',
            field=models.DecimalField(decimal_places=1, default=8, help_text='Standard working hours per day. Hours worked beyond this count as overtime.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='projectholiday',
            name='applied',
            field=models.BooleanField(default=False, help_text="True once the holiday has been applied to all workers' attendance"),
        ),
        migrations.AlterField(
            model_name='projectholiday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
