# Generated by Django 4.2.9 on 2026-05-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_projectattendancesettings_sound_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattendancesettings',
            name='sound_pitch',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Pitch multiplier for chime sounds (0.5 to 2.0)', max_digits=3),
        ),
        migrations.AddField(
            model_name='projectattendancesettings',
            name='voice_pitch',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Speech pitch for voice announcements (0.0 to 2.0)', max_digits=3),
        ),
    ]
