# Generated by Django 4.2.9 on 2026-05-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_mqttconfig_mqttscanevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mqttscanevent',
            new_name='attendance__config__5cafc6_idx',
            old_name='attendance_mqtt_cfg_recv_idx',
        ),
        migrations.RenameIndex(
            model_name='mqttscanevent',
            new_name='attendance__nfc_uid_76991e_idx',
            old_name='attendance_mqtt_uid_idx',
        ),
        migrations.AlterField(
            model_name='mqttconfig',
            name='topic',
            field=models.CharField(default='nfc/+/state', help_text='MQTT topic pattern.  Use + for single-level wildcard, # for multi-level.  Example: nfc/+/state', max_length=255),
        ),
        migrations.AlterField(
            model_name='mqttscanevent',
            name='message',
            field=models.CharField(blank=True, help_text="Human-readable result (e.g. 'Check-in recorded for John Doe')", max_length=500),
        ),
    ]
