# Generated by Django 4.2.9 on 2026-05-05 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('attendance', '0011_nfcdevice_mqttscanevent_v2_telemetry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nfcdevice',
            new_name='attendance__project_4d5bdf_idx',
            old_name='attendance__nfc_dev_proj_idx',
        ),
        migrations.AlterField(
            model_name='nfcdevice',
            name='ip_address',
            field=models.CharField(blank=True, help_text='Last known IP address (IPv4 or IPv6)', max_length=45),
        ),
        migrations.AlterField(
            model_name='nfcdevice',
            name='last_seen',
            field=models.DateTimeField(auto_now=True, help_text='Automatically updated on every announce or scan event'),
        ),
        migrations.AlterField(
            model_name='nfcdevice',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this device belongs to (matched by project_id from announce)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_devices', to='core.houseproject'),
        ),
        migrations.AlterField(
            model_name='nfcdevice',
            name='total_scans',
            field=models.PositiveIntegerField(default=0, help_text='Total scan events received from this device since tracking started'),
        ),
    ]
