# Generated by Django 4.2.9 on 2026-05-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_attendanceworker_working_days_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttscanevent',
            name='device_timestamp',
            field=models.DateTimeField(blank=True, help_text='Original scan time from the device (ts field). Non-null only for queued=1 scans replayed after reconnect. Use this instead of received_at for attendance-time display.', null=True),
        ),
    ]
