# Generated by Django 4.2.9 on 2026-05-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_nfc_sync_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceworker',
            name='nfc_uid_updated_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp when nfc_uid was last assigned or changed.  Compare against NFCDevice.last_push_at to know if this worker's card is already loaded on every device.", null=True),
        ),
        migrations.AlterField(
            model_name='nfcdevice',
            name='last_push_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp of the last successful users/sync push to this device.  Compare against AttendanceWorker.nfc_uid_updated_at to determine whether a worker's card is already on this device.", null=True),
        ),
    ]
