# Generated by Django 4.2.9 on 2026-05-15 01:39
# Edited: null-out old integer contractor_id values before altering to UUID FK.
# Old contractor_id pointed to resources.Contractor (integer PK).
# New contractor_id points to resource.Worker (UUID PK) — no value mapping possible.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_stockmovement_delivered_by_and_more'),
        ('attendance', '0018_backfill_nfc_uid_updated_at'),
    ]

    operations = [
        # Step 1: clear all old integer contractor_id values so the column
        # can be safely retyped to UUID without FK constraint violations.
        migrations.RunSQL(
            sql="UPDATE attendance_attendanceworker SET contractor_id = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Step 2: alter the column to point at resource.Worker (UUID PK).
        migrations.AlterField(
            model_name='attendanceworker',
            name='contractor',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='attendance_worker',
                to='resource.worker',
                help_text='Linked resource worker record for this attendance worker',
            ),
        ),
    ]
