# Generated by Django 4.2.9 on 2026-05-15 01:39
# Fixed: PostgreSQL cannot cast bigint → uuid via ALTER COLUMN … USING.
# Strategy: drop old integer FK column, re-add as fresh uuid FK column.
# Old contractor_id → resources.Contractor (integer PK).
# New contractor_id → resource.Worker (UUID PK). No value mapping possible.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_stockmovement_delivered_by_and_more'),
        ('attendance', '0018_backfill_nfc_uid_updated_at'),
    ]

    operations = [
        # Drop old bigint contractor_id column (CASCADE removes FK + unique constraints).
        migrations.RunSQL(
            sql='ALTER TABLE attendance_attendanceworker DROP COLUMN IF EXISTS contractor_id CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Re-add as a uuid FK column with unique constraint (OneToOneField).
        migrations.RunSQL(
            sql="""
                ALTER TABLE attendance_attendanceworker
                    ADD COLUMN contractor_id uuid NULL
                    REFERENCES resource_worker (id)
                    ON DELETE SET NULL
                    DEFERRABLE INITIALLY DEFERRED;
                CREATE UNIQUE INDEX IF NOT EXISTS
                    attendance_attendanceworker_contractor_id_key
                    ON attendance_attendanceworker (contractor_id)
                    WHERE contractor_id IS NOT NULL;
            """,
            reverse_sql='ALTER TABLE attendance_attendanceworker DROP COLUMN IF EXISTS contractor_id CASCADE;',
        ),

        # Tell Django's state machine the field is now a OneToOneField to resource.Worker.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='attendanceworker',
                    name='contractor',
                    field=models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='attendance_worker',
                        to='resource.worker',
                        help_text='Linked resource worker record for this attendance worker',
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
