# Generated by Django 4.2.9 on 2026-05-15 01:39
# Fixed: PostgreSQL cannot cast bigint → uuid via ALTER COLUMN … USING.
# Strategy: drop old integer FK column, re-add as fresh uuid FK column.
# Old contractor_id → resources.Contractor (integer PK).
# New contractor_id → resource.Worker (UUID PK). No value mapping possible.
#
# SQLite compatibility: IF EXISTS / CASCADE / DEFERRABLE are PG-only.
# RunPython with vendor detection keeps both backends happy.
# The conditional unique index uses IF NOT EXISTS + WHERE — works on both.

from django.db import migrations, models
import django.db.models.deletion


def _drop_col(table, col):
    def forward(apps, schema_editor):
        vendor = schema_editor.connection.vendor
        with schema_editor.connection.cursor() as cur:
            if vendor == 'sqlite':
                cur.execute(f'PRAGMA table_info("{table}")')
                if col in [r[1] for r in cur.fetchall()]:
                    cur.execute(f'ALTER TABLE "{table}" DROP COLUMN "{col}"')
            else:
                cur.execute(f'ALTER TABLE "{table}" DROP COLUMN IF EXISTS "{col}" CASCADE')
    return forward


def _add_uuid_fk(table, col, ref_table, null=True, on_delete='SET NULL'):
    null_kw = 'NULL' if null else 'NOT NULL'
    def forward(apps, schema_editor):
        vendor = schema_editor.connection.vendor
        with schema_editor.connection.cursor() as cur:
            if vendor == 'sqlite':
                cur.execute(f'ALTER TABLE "{table}" ADD COLUMN "{col}" TEXT {null_kw}')
            else:
                cur.execute(f'''
                    ALTER TABLE "{table}"
                        ADD COLUMN "{col}" uuid {null_kw}
                        REFERENCES "{ref_table}" (id)
                        ON DELETE {on_delete}
                        DEFERRABLE INITIALLY DEFERRED
                ''')
    return forward


def _create_partial_unique_index(index_name, table, col):
    """Partial unique index: unique where col IS NOT NULL. Works on both SQLite and PG."""
    def forward(apps, schema_editor):
        with schema_editor.connection.cursor() as cur:
            cur.execute(
                f'CREATE UNIQUE INDEX IF NOT EXISTS "{index_name}" '
                f'ON "{table}" ("{col}") WHERE "{col}" IS NOT NULL'
            )
    def reverse(apps, schema_editor):
        with schema_editor.connection.cursor() as cur:
            cur.execute(f'DROP INDEX IF EXISTS "{index_name}"')
    return forward, reverse


_idx_fwd, _idx_rev = _create_partial_unique_index(
    'attendance_attendanceworker_contractor_id_key',
    'attendance_attendanceworker',
    'contractor_id',
)


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_stockmovement_delivered_by_and_more'),
        ('attendance', '0018_backfill_nfc_uid_updated_at'),
    ]

    operations = [
        # Drop old bigint contractor_id column.
        migrations.RunPython(
            _drop_col('attendance_attendanceworker', 'contractor_id'),
            migrations.RunPython.noop,
        ),

        # Re-add as a uuid FK column (nullable).
        migrations.RunPython(
            _add_uuid_fk('attendance_attendanceworker', 'contractor_id', 'resource_worker'),
            migrations.RunPython.noop,
        ),

        # Partial unique index (OneToOneField semantics, allows multiple NULLs).
        migrations.RunPython(_idx_fwd, _idx_rev),

        # Tell Django's state machine the field is now a OneToOneField to resource.Worker.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='attendanceworker',
                    name='contractor',
                    field=models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='attendance_worker',
                        to='resource.worker',
                        help_text='Linked resource worker record for this attendance worker',
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
