FROM oven/bun:1 as base

WORKDIR /app

# Copy package files
COPY package.json bun.lockb ./

# Install dependencies
RUN bun install --frozen-lockfile

EXPOSE 5173

CMD ["bun", "run", "dev", "--", "--host"]
