# Generated by Django 4.2.9 on 2026-04-22 12:36

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emaillog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorPaymentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('work_completion_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of phase completed', max_digits=5)),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('retention_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount withheld', max_digits=15)),
                ('net_payable', models.DecimalField(decimal_places=2, help_text='Claimed - Retention', max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to='accounting.vendor')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='core.constructionphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='core.houseproject')),
                ('vendor_bill', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.vendorbill')),
            ],
        ),
        migrations.CreateModel(
            name='RetentionRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_releases', to='accounting.contractorpaymentrequest')),
                ('vendor_bill', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.vendorbill')),
            ],
        ),
        migrations.CreateModel(
            name='PhaseBudgetLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.constructionphase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.houseproject')),
            ],
            options={
                'ordering': ['phase__order'],
                'unique_together': {('project', 'phase')},
            },
        ),
        migrations.CreateModel(
            name='BudgetRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('previous_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.CharField(max_length=500)),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='accounting.phasebudgetline')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
