# Generated by Django 5.2.13 on 2026-04-22 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_contractorpaymentrequest_retentionrelease_and_more'),
        ('core', '0006_add_project_fk_to_phase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billpayment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='vendorbill',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='billpayment',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_purchase_orders', to='core.constructionphase'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_purchase_orders', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Civil Contractor, Electrical, Material Supplier, Labor', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN/VAT registration number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='reference',
            field=models.CharField(blank=True, help_text='Cheque/transfer no.', max_length=255, null=True),
        ),
    ]
