# Generated by Django 4.2.9 on 2026-04-29 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorpaymentrequest',
            name='finance_bill_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_payment_request', to='finance.billpayment'),
        ),
        migrations.AddField(
            model_name='contractorpaymentrequest',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='core.constructionphase'),
        ),
        migrations.AddField(
            model_name='contractorpaymentrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='contractorpaymentrequest',
            name='vendor_bill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.vendorbill'),
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='from_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='cashtransfer',
            name='to_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='capitalsource',
            name='gl_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_sources', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='budgetrevision',
            name='budget_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='accounting.phasebudgetline'),
        ),
        migrations.AddField(
            model_name='budgetrevision',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.vendorbill'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='account',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_accounts', to='core.houseproject'),
        ),
        migrations.AlterUniqueTogether(
            name='phasebudgetline',
            unique_together={('project', 'phase')},
        ),
    ]
