# Generated by Django 4.2.9 on 2026-04-23 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_floor_project'),
        ('accounting', '0003_add_vendor_fields_and_po_related_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='capitalsource',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capital_sources', to='core.houseproject'),
        ),
    ]
