# Generated by Django 4.2.9 on 2026-04-23 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_bankaccount_project_capitalsource_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitalsource',
            name='project',
        ),
    ]
