# Generated by Django 4.2.9 on 2026-04-23 05:16

from django.db import migrations

def merge_suppliers(apps, schema_editor):
    Supplier = apps.get_model('resources', 'Supplier')
    Vendor = apps.get_model('accounting', 'Vendor')
    Material = apps.get_model('resources', 'Material')
    MaterialTransaction = apps.get_model('resources', 'MaterialTransaction')
    Expense = apps.get_model('finance', 'Expense')

    # Iterate over all Suppliers and port them to Vendors
    for supplier in Supplier.objects.all():
        vendor = Vendor.objects.create(
            name=supplier.name,
            contact_person=supplier.contact_person,
            email=supplier.email,
            phone=supplier.phone,
            address=supplier.address,
            photo=supplier.photo,
            is_active=supplier.is_active,
            category=supplier.category,
            pan_number=supplier.pan_number,
            bank_name=supplier.bank_name,
            account_number=supplier.account_number,
            branch=supplier.branch,
        )
        
        # Update foreign keys using the new UUID
        Material.objects.filter(supplier=supplier).update(vendor=vendor)
        MaterialTransaction.objects.filter(supplier=supplier).update(vendor=vendor)
        Expense.objects.filter(supplier=supplier).update(vendor=vendor)

def reverse_merge(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_vendor_account_number_vendor_bank_name_vendor_branch_and_more'),
        ('resources', '0010_material_vendor_materialtransaction_vendor'),
        ('finance', '0015_expense_vendor_historicalexpense_vendor'),
    ]

    operations = [
        migrations.RunPython(merge_suppliers, reverse_merge),
    ]
