# Generated by Django 4.2.9 on 2026-04-23 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_billpayment_project'),
        ('accounting', '0007_merge_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorpaymentrequest',
            name='finance_bill_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_payment_request', to='finance.billpayment'),
        ),
    ]
