# Generated by Django 4.2.9 on 2026-04-23 22:27

from django.db import migrations, models
import django.db.models.deletion

def migrate_data(apps, schema_editor):
    try:
        BankAccount = apps.get_model('accounting', 'BankAccount')
        Account = apps.get_model('accounting', 'Account')
        BillPayment = apps.get_model('accounting', 'BillPayment')
        CashTransfer = apps.get_model('accounting', 'CashTransfer')
        
        for bank in BankAccount.objects.all():
            # In the migration context, we use the FK IDs directly
            acc_id = bank.gl_account_id
            Account.objects.filter(id=acc_id).update(
                project_id=bank.project_id,
                bank_name=bank.name,
                account_number=bank.account_number
            )
            
            # Update BillPayments pointing to BankAccount to point to Account
            BillPayment.objects.filter(bank_account_id=bank.id).update(bank_account_id=acc_id)
            
            # Update CashTransfers
            CashTransfer.objects.filter(from_bank_id=bank.id).update(from_bank_id=acc_id)
            CashTransfer.objects.filter(to_bank_id=bank.id).update(to_bank_id=acc_id)
    except Exception as e:
        print(f"Data migration warning: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_floor_project'),
        ('accounting', '0008_contractorpaymentrequest_finance_bill_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_accounts', to='core.houseproject'),
        ),
        # Run data migration BEFORE changing FK constraints
        migrations.RunPython(migrate_data),
        
        migrations.AlterField(
            model_name='billpayment',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='cashtransfer',
            name='from_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='cashtransfer',
            name='to_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='accounting.account'),
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
