# Generated by Django 4.2.9 on 2026-04-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_account_account_number_account_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_bank',
            field=models.BooleanField(default=False, help_text='If true, this account will appear in Treasury/Bank views'),
        ),
    ]
