# Generated by Django 4.2.9 on 2026-04-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_account_is_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual interest rate for loans', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_loan',
            field=models.BooleanField(default=False, help_text='If true, this account will appear in Loan/Liability views'),
        ),
    ]
