# Generated by Django 4.2.9 on 2026-04-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_account_account_holder_name_account_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='emi_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly EMI amount', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='loan_tenure_months',
            field=models.IntegerField(blank=True, help_text='Total duration of loan in months', null=True),
        ),
    ]
