# Generated by Django 4.2.9 on 2026-04-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_account_emi_amount_account_loan_tenure_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_loan_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total approved loan amount (Credit Limit)', max_digits=15, null=True),
        ),
    ]
