# Generated by Django 4.2.9 on 2026-05-10 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPresenceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_at', models.DateTimeField()),
                ('exit_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='True if the user is currently on site')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_sessions', to='core.houseproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-entry_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGeofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('radius_meters', models.PositiveIntegerField(default=100, help_text='Radius around the center point in meters')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geofence', to='core.houseproject')),
            ],
            options={
                'verbose_name': 'Project Geofence',
                'verbose_name_plural': 'Project Geofences',
            },
        ),
        migrations.CreateModel(
            name='StaffLocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('accuracy', models.FloatField(help_text='Accuracy in meters')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_on_site', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_pings', to='core.houseproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='location_tr_user_id_0a34d2_idx')],
            },
        ),
    ]
