# Generated by Django 4.2.9 on 2026-05-10 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_tracking', '0002_upgrade_location_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='stafflocationlog',
            new_name='location_tr_project_9f0a3b_idx',
            old_name='loc_log_project_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='staffpresencesession',
            new_name='location_tr_is_acti_60260f_idx',
            old_name='loc_session_active_proj_idx',
        ),
        migrations.RenameIndex(
            model_name='staffpresencesession',
            new_name='location_tr_user_id_b8d3f0_idx',
            old_name='loc_session_user_entry_idx',
        ),
    ]
