# Generated by Django 4.2.9 on 2026-05-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_tracking', '0004_projectsitepin'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectsitepin',
            new_name='location_tr_project_3061e5_idx',
            old_name='loc_pin_project_active_idx',
        ),
    ]
