# Generated by Django 4.2.9 on 2026-04-28 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0006_attendanceworker_contractor'),
        ('core', '0018_projectmember_permission_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(blank=True, help_text='The person in charge of this team', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to='attendance.attendanceworker')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to='attendance.attendanceworker')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.houseproject')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
