# Generated by Django 4.2.9 on 2026-02-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Foundation, Structure, Electrical', max_length=100, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('HALTED', 'Halted')], default='PENDING', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of execution')),
                ('description', models.TextField(blank=True)),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HouseProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My House Configuration', max_length=200)),
                ('owner_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('total_budget', models.DecimalField(decimal_places=2, help_text='Total allocated budget for the project', max_digits=12)),
                ('start_date', models.DateField()),
                ('expected_completion_date', models.DateField()),
                ('area_sqft', models.IntegerField(help_text='Total build area in square feet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'House Project Configuration',
                'verbose_name_plural': 'House Project Configuration',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Master Bedroom, Kitchen', max_length=100)),
                ('floor', models.IntegerField(choices=[(0, 'Ground Floor'), (1, 'First Floor'), (2, 'Second Floor'), (3, 'Third Floor'), (-1, 'Basement'), (99, 'Outdoor/Exterior')], default=0)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('budget_allocation', models.DecimalField(decimal_places=2, default=0.0, help_text='Budget for finishing/interiors', max_digits=12)),
            ],
        ),
    ]
