# Generated by Django 4.2.9 on 2026-02-23 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Jag Khanne, DPC, Piller Thadaune, Slab Dhalaan', max_length=100, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('HALTED', 'Halted')], default='PENDING', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of execution')),
                ('description', models.TextField(blank=True)),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('permit_required', models.BooleanField(default=False, help_text='Does this phase require municipal permit approval?')),
                ('permit_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUIRED', help_text='Status of municipal permit for this phase', max_length=20)),
                ('permit_date_issued', models.DateField(blank=True, help_text='Date when permit was approved', null=True)),
                ('permit_notes', models.TextField(blank=True, help_text='Notes about permit process, requirements, or issues')),
                ('naksa_file', models.FileField(blank=True, help_text='Blueprints/Naksa for this phase', null=True, upload_to='phases/naksa/')),
                ('structure_design', models.FileField(blank=True, help_text='Structural design documents', null=True, upload_to='phases/structure/')),
                ('completion_photo', models.ImageField(blank=True, help_text='Photo proof after phase completion', null=True, upload_to='phases/completion/')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Ground Floor, First Floor', max_length=100)),
                ('level', models.IntegerField(default=0, help_text='Level for sorting (0=Ground, 1=First, etc.)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='floor_plans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='HouseProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mero Ghar Construction', max_length=200)),
                ('owner_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('total_budget', models.DecimalField(decimal_places=2, help_text='Total allocated budget (Rs.)', max_digits=12)),
                ('start_date', models.DateField()),
                ('expected_completion_date', models.DateField()),
                ('area_sqft', models.IntegerField(help_text='Total build area in square feet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'House Project Configuration',
                'verbose_name_plural': 'House Project Configuration',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Puja Kotha, Bhansa, Baithak', max_length=100)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Suru Bhayena'), ('IN_PROGRESS', 'Kaam Hudai Cha'), ('COMPLETED', 'Sakiya')], default='NOT_STARTED', max_length=20)),
                ('budget_allocation', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.floor')),
            ],
        ),
    ]
