# Generated by Django 4.2.9 on 2026-04-03 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique key for the guide (e.g., 'home', 'stock')", max_length=50, unique=True)),
                ('icon', models.CharField(default='ℹ️', max_length=10)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ne', models.CharField(max_length=200)),
                ('description_en', models.TextField()),
                ('description_ne', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Guide',
                'verbose_name_plural': 'User Guides',
            },
        ),
        migrations.CreateModel(
            name='UserGuideStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text_en', models.TextField()),
                ('text_ne', models.TextField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.userguide')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserGuideFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_en', models.TextField()),
                ('question_ne', models.TextField()),
                ('answer_en', models.TextField()),
                ('answer_ne', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='core.userguide')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
