# Generated by Django 4.2.9 on 2026-02-10 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Ground Floor, First Floor', max_length=100)),
                ('level', models.IntegerField(default=0, help_text='Level for sorting (0=Ground, 1=First, etc.)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='floor_plans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.AlterField(
            model_name='constructionphase',
            name='name',
            field=models.CharField(help_text='e.g., Jag Khanne, DPC, Piller Thadaune, Slab Dhalaan', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='houseproject',
            name='name',
            field=models.CharField(default='Mero Ghar Construction', max_length=200),
        ),
        migrations.AlterField(
            model_name='houseproject',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, help_text='Total allocated budget (Rs.)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='room',
            name='budget_allocation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='e.g., Puja Kotha, Bhansa, Baithak', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Suru Bhayena'), ('IN_PROGRESS', 'Kaam Hudai Cha'), ('COMPLETED', 'Sakiya')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.floor'),
        ),
    ]
