# Generated by Django 4.2.9 on 2026-04-05 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_userguide_userguidestep_userguidefaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='userguide',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this guide is active and should be shown.'),
        ),
        migrations.AddField(
            model_name='userguide',
            name='type',
            field=models.CharField(choices=[('modal', 'Modal Dialog'), ('tour', 'Interactive Tour'), ('sidebar', 'Sidebar Content')], default='modal', help_text='How the guide should be displayed in the frontend.', max_length=20),
        ),
        migrations.AddField(
            model_name='userguide',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional link to a video tutorial.'),
        ),
        migrations.AddField(
            model_name='userguidestep',
            name='media',
            field=models.FileField(blank=True, help_text='Image or GIF to show in the step.', null=True, upload_to='guides/steps/'),
        ),
        migrations.AddField(
            model_name='userguidestep',
            name='placement',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right'), ('center', 'Center')], help_text='Tooltip placement for tour libraries.', max_length=20),
        ),
        migrations.AddField(
            model_name='userguidestep',
            name='target_element',
            field=models.CharField(blank=True, help_text="CSS selector for the element to highlight (e.g., '#add-btn').", max_length=255),
        ),
        migrations.CreateModel(
            name='UserGuideProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('last_step_seen', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.userguide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'guide')},
            },
        ),
    ]
