# Generated by Django 4.2.9 on 2026-05-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionphase',
            name='technical_spec',
            field=models.TextField(blank=True, help_text="Engineer's instructions on how to finish this phase"),
        ),
    ]
