# Generated by Django 4.2.9 on 2026-05-14 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('NAKSA', 'Naksa / Blueprint'), ('STRUCTURE', 'Structural Design'), ('OTHER', 'Other Document')], default='OTHER', max_length=20)),
                ('file', models.FileField(upload_to='phases/documents/')),
                ('name', models.CharField(blank=True, help_text='Original filename or custom name', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.constructionphase')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
