# Generated by Django 4.2.9 on 2026-02-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_constructionphasemedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConstructionPhaseMedia',
        ),
    ]
