# Generated by Django 4.2.9 on 2026-05-14 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_phasedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phasedocument',
            name='document_type',
            field=models.CharField(choices=[('NAKSA', 'Naksa / Blueprint'), ('STRUCTURE', 'Structural Design'), ('3D_MODEL', '3D Model / Design'), ('OTHER', 'Other Document')], default='OTHER', max_length=20),
        ),
    ]
