# Generated by Django 4.2.9 on 2026-04-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userguide_is_active_userguide_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userguide',
            options={'ordering': ['order'], 'verbose_name': 'User Guide', 'verbose_name_plural': 'User Guides'},
        ),
        migrations.AddField(
            model_name='userguide',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
