# Generated by Django 4.2.9 on 2026-05-15 01:45
# Fixed: PostgreSQL cannot cast bigint → uuid via ALTER COLUMN … USING.
# Strategy: drop the old integer FK column, add a fresh uuid FK column.
# All existing material_id values were integers pointing at the old
# resources.Material table (different app); no value mapping is possible,
# so the column is simply recreated as nullable with no data loss risk.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_stockmovement_delivered_by_and_more'),
        ('core', '0004_alter_phasedocument_document_type'),
    ]

    operations = [
        # Step 1: drop the old bigint material_id column (and any FK constraint
        # Django or the DB created for it).  CASCADE handles the constraint.
        migrations.RunSQL(
            sql="ALTER TABLE core_emaillog DROP COLUMN IF EXISTS material_id CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Step 2: add the new uuid FK column pointing at resource.Material.
        migrations.RunSQL(
            sql="""
                ALTER TABLE core_emaillog
                    ADD COLUMN material_id uuid NULL
                    REFERENCES resource_material (id)
                    ON DELETE SET NULL
                    DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="ALTER TABLE core_emaillog DROP COLUMN IF EXISTS material_id CASCADE;",
        ),

        # Step 3: tell Django's state machine the field is now a proper FK so
        # subsequent migrations and the ORM see the correct field type.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='emaillog',
                    name='material',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='email_logs',
                        to='resource.material',
                    ),
                ),
            ],
            database_operations=[],   # already done above
        ),
    ]
