# Generated by Django 4.2.9 on 2026-05-15 01:45
# Edited: null-out old integer material_id before altering to UUID FK.
# Old material_id pointed to resources.Material (integer PK).
# New material_id points to resource.Material (UUID PK) — no value mapping possible.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_stockmovement_delivered_by_and_more'),
        ('core', '0004_alter_phasedocument_document_type'),
    ]

    operations = [
        # Step 1: clear old integer material_id values before retyping to UUID.
        migrations.RunSQL(
            sql="UPDATE core_emaillog SET material_id = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Step 2: alter column to point at resource.Material (UUID PK).
        migrations.AlterField(
            model_name='emaillog',
            name='material',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='email_logs',
                to='resource.material',
            ),
        ),
    ]
