# Generated by Django 4.2.9 on 2026-02-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_constructionphasemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionphase',
            name='completion_photo',
            field=models.ImageField(blank=True, help_text='Photo proof after phase completion', null=True, upload_to='phases/completion/'),
        ),
        migrations.AddField(
            model_name='constructionphase',
            name='naksa_file',
            field=models.FileField(blank=True, help_text='Blueprints/Naksa for this phase', null=True, upload_to='phases/naksa/'),
        ),
        migrations.AddField(
            model_name='constructionphase',
            name='structure_design',
            field=models.FileField(blank=True, help_text='Structural design documents', null=True, upload_to='phases/structure/'),
        ),
    ]
