# Generated by Django 4.2.9 on 2026-02-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_constructionphase_completion_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionphase',
            name='permit_date_issued',
            field=models.DateField(blank=True, help_text='Date when permit was approved', null=True),
        ),
        migrations.AddField(
            model_name='constructionphase',
            name='permit_notes',
            field=models.TextField(blank=True, help_text='Notes about permit process, requirements, or issues'),
        ),
        migrations.AddField(
            model_name='constructionphase',
            name='permit_required',
            field=models.BooleanField(default=False, help_text='Does this phase require municipal permit approval?'),
        ),
        migrations.AddField(
            model_name='constructionphase',
            name='permit_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_REQUIRED', help_text='Status of municipal permit for this phase', max_length=20),
        ),
    ]
