# Generated by Django 5.2.13 on 2026-04-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionphase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='core.houseproject'),
        ),
        migrations.AlterField(
            model_name='constructionphase',
            name='name',
            field=models.CharField(help_text='e.g., Jag Khanne, DPC, Piller Thadaune, Slab Dhalaan', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='constructionphase',
            unique_together={('project', 'name')},
        ),
    ]
