from django.db import migrations, models


DEFAULT_PROJECT_ROLES = [
    {
        "code": "OWNER",
        "name": "Owner",
        "name_ne": "मालिक",
        "description": "Full project control",
        "description_ne": "पूरा परियोजना नियन्त्रण",
        "icon": "👑",
        "color": "#f97316",
        "sort_order": 10,
        "is_system": True,
        "is_active": True,
        "can_manage_members": True,
        "can_manage_finances": True,
        "can_view_finances": True,
        "can_manage_phases": True,
        "can_manage_structure": True,
        "can_manage_resources": True,
        "can_upload_media": True,
        "can_manage_workforce": True,
        "can_approve_purchases": True,
    },
    {
        "code": "MANAGER",
        "name": "Project Manager",
        "name_ne": "परियोजना प्रबन्धक",
        "description": "Operational control and approvals",
        "description_ne": "सञ्चालन नियन्त्रण र स्वीकृति",
        "icon": "🧑‍💼",
        "color": "#3b82f6",
        "sort_order": 20,
        "is_system": True,
        "is_active": True,
        "can_manage_members": True,
        "can_manage_finances": True,
        "can_view_finances": True,
        "can_manage_phases": True,
        "can_manage_structure": True,
        "can_manage_resources": True,
        "can_upload_media": True,
        "can_manage_workforce": True,
        "can_approve_purchases": True,
    },
    {
        "code": "ENGINEER",
        "name": "Engineer",
        "name_ne": "इन्जिनियर",
        "description": "Phases, structure, and resource requests",
        "description_ne": "फेज, संरचना र स्रोत अनुरोध",
        "icon": "🔧",
        "color": "#8b5cf6",
        "sort_order": 30,
        "is_system": True,
        "is_active": True,
        "can_manage_members": False,
        "can_manage_finances": False,
        "can_view_finances": True,
        "can_manage_phases": True,
        "can_manage_structure": True,
        "can_manage_resources": True,
        "can_upload_media": True,
        "can_manage_workforce": False,
        "can_approve_purchases": False,
    },
    {
        "code": "SUPERVISOR",
        "name": "Supervisor",
        "name_ne": "सुपरभाइजर",
        "description": "Site execution and workforce tracking",
        "description_ne": "साइट सञ्चालन र कार्यबल ट्र्याकिङ",
        "icon": "🦺",
        "color": "#f59e0b",
        "sort_order": 40,
        "is_system": True,
        "is_active": True,
        "can_manage_members": False,
        "can_manage_finances": False,
        "can_view_finances": True,
        "can_manage_phases": True,
        "can_manage_structure": False,
        "can_manage_resources": False,
        "can_upload_media": True,
        "can_manage_workforce": True,
        "can_approve_purchases": False,
    },
    {
        "code": "CONTRACTOR",
        "name": "Contractor",
        "name_ne": "ठेकेदार",
        "description": "Resources and media updates",
        "description_ne": "स्रोतसाधन र मिडिया अपडेट",
        "icon": "🏗️",
        "color": "#10b981",
        "sort_order": 50,
        "is_system": True,
        "is_active": True,
        "can_manage_members": False,
        "can_manage_finances": False,
        "can_view_finances": False,
        "can_manage_phases": False,
        "can_manage_structure": False,
        "can_manage_resources": True,
        "can_upload_media": True,
        "can_manage_workforce": False,
        "can_approve_purchases": False,
    },
    {
        "code": "VIEWER",
        "name": "Viewer",
        "name_ne": "दर्शक",
        "description": "Read-only project access",
        "description_ne": "हेर्न मात्र मिल्ने परियोजना पहुँच",
        "icon": "👁️",
        "color": "#64748b",
        "sort_order": 60,
        "is_system": True,
        "is_active": True,
        "can_manage_members": False,
        "can_manage_finances": False,
        "can_view_finances": True,
        "can_manage_phases": False,
        "can_manage_structure": False,
        "can_manage_resources": False,
        "can_upload_media": False,
        "can_manage_workforce": False,
        "can_approve_purchases": False,
    },
]


def seed_project_roles(apps, schema_editor):
    ProjectRole = apps.get_model("core", "ProjectRole")
    for payload in DEFAULT_PROJECT_ROLES:
        ProjectRole.objects.update_or_create(code=payload["code"], defaults=payload)


def unseed_project_roles(apps, schema_editor):
    ProjectRole = apps.get_model("core", "ProjectRole")
    ProjectRole.objects.filter(code__in=[item["code"] for item in DEFAULT_PROJECT_ROLES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_emaillog_material_switch_to_resource"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectRole",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("name_ne", models.CharField(blank=True, default="", max_length=80)),
                ("description", models.CharField(blank=True, default="", max_length=220)),
                ("description_ne", models.CharField(blank=True, default="", max_length=220)),
                ("icon", models.CharField(blank=True, default="", max_length=8)),
                ("color", models.CharField(blank=True, default="", max_length=20)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("can_manage_members", models.BooleanField(default=False)),
                ("can_manage_finances", models.BooleanField(default=False)),
                ("can_view_finances", models.BooleanField(default=False)),
                ("can_manage_phases", models.BooleanField(default=False)),
                ("can_manage_structure", models.BooleanField(default=False)),
                ("can_manage_resources", models.BooleanField(default=False)),
                ("can_upload_media", models.BooleanField(default=False)),
                ("can_manage_workforce", models.BooleanField(default=False)),
                ("can_approve_purchases", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Project Role",
                "verbose_name_plural": "Project Roles",
                "ordering": ["sort_order", "name", "code"],
            },
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="role",
            field=models.CharField(default="VIEWER", max_length=50),
        ),
        migrations.RunPython(seed_project_roles, unseed_project_roles),
    ]
