# Generated by Django 4.2.9 on 2026-04-23 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_floor_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='project',
        ),
    ]
