# Generated by Django 4.2.9 on 2026-04-23 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_room_polygon_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='core.houseproject'),
        ),
    ]
