# Generated by Django 4.2.9 on 2026-04-25 21:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_projectmember'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectmember',
            name='unique_project_user',
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'user')},
        ),
    ]
