# Generated by Django 4.2.9 on 2026-04-26 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userguide_sections_and_contributor_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userguidefaq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 26, 14, 5, 28, 691360, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userguidesection',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Admins can hide contributed sections.'),
        ),
        migrations.AlterField(
            model_name='userguidestep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 26, 14, 5, 35, 352407, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userguidestep',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='guides/steps/'),
        ),
        migrations.AlterField(
            model_name='userguidestep',
            name='placement',
            field=models.CharField(blank=True, choices=[('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right'), ('center', 'Center')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userguidestep',
            name='target_element',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
