# Generated by Django 5.2.13 on 2026-04-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_userguidefaq_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='can_manage_finances',
            field=models.BooleanField(default=False, help_text='Create / edit expenses, budgets, payments'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_manage_members',
            field=models.BooleanField(default=False, help_text='Add / remove / edit team members'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_manage_phases',
            field=models.BooleanField(default=False, help_text='Create / edit phases and tasks'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_manage_resources',
            field=models.BooleanField(default=False, help_text='Create / edit materials, contractors, suppliers'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_manage_structure',
            field=models.BooleanField(default=False, help_text='Create / edit floors and rooms'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_upload_media',
            field=models.BooleanField(default=False, help_text='Upload photos and documents'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='can_view_finances',
            field=models.BooleanField(default=False, help_text='Read-only access to financial data'),
        ),
    ]
