# Generated by Django 4.2.9 on 2026-05-18 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_emaillog_material_switch_to_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('workforce', 'Workforce Members'), ('materials', 'Materials / Inventory'), ('attendance', 'Attendance Records'), ('suppliers', 'Suppliers')], max_length=32)),
                ('file_name', models.CharField(max_length=255)),
                ('file_format', models.CharField(default='csv', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dry_run', 'Dry Run'), ('importing', 'Importing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_imported', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='core.houseproject')),
            ],
            options={
                'verbose_name': 'Import Job',
                'verbose_name_plural': 'Import Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
