# Generated by Django 4.2.9 on 2026-05-01 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Finalized'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10)),
                ('quality_tier', models.CharField(choices=[('ECONOMY', 'Economy'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('LUXURY', 'Luxury')], default='STANDARD', max_length=10)),
                ('total_area_sqft', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('floors', models.PositiveSmallIntegerField(default=1)),
                ('bedrooms', models.PositiveSmallIntegerField(default=2)),
                ('bathrooms', models.PositiveSmallIntegerField(default=1)),
                ('include_mep', models.BooleanField(default=True)),
                ('include_finishing', models.BooleanField(default=True)),
                ('contingency_pct', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('material_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('labor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contingency_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='core.houseproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LaborRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(choices=[('MASON', 'Mason (Dakarmi)'), ('HELPER', 'Helper (Jugi)'), ('CARPENTER', 'Carpenter (Mistri)'), ('ELECTRICIAN', 'Electrician'), ('PLUMBER', 'Plumber'), ('PAINTER', 'Painter'), ('STEEL_FIXER', 'Steel Fixer (Lohari)'), ('SUPERVISOR', 'Site Supervisor'), ('TILE_SETTER', 'Tile Setter'), ('EXCAVATOR', 'Excavator Operator'), ('WATERPROOF', 'Waterproofing Applicator')], max_length=20, unique=True)),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Rate per day in NPR', max_digits=10)),
                ('region', models.CharField(default='Kathmandu', max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['trade'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Canonical key used in formulas e.g. CEMENT, ROD', max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('CEMENT', 'Cement'), ('SAND', 'Sand'), ('AGGREGATE', 'Aggregate / Gitti'), ('BRICK', 'Brick / Itta'), ('STEEL', 'Steel / Rod'), ('PAINT', 'Paint'), ('TILE', 'Tile / Flooring'), ('PLUMBING', 'Plumbing Material'), ('ELECTRICAL', 'Electrical Material'), ('TIMBER', 'Timber / Wood'), ('GLASS', 'Glass'), ('WATERPROOF', 'Waterproofing'), ('OTHER', 'Other')], max_length=15)),
                ('unit', models.CharField(choices=[('BAG', 'Bag (50 kg)'), ('CFT', 'Cubic Feet'), ('M3', 'Cubic Metre'), ('KG', 'Kilogram'), ('TON', 'Metric Ton'), ('PCS', 'Pieces'), ('SQFT', 'Square Feet'), ('SQM', 'Square Metre'), ('LFT', 'Linear Feet'), ('LM', 'Linear Metre'), ('LITR', 'Litre'), ('SET', 'Set')], max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Current market price in NPR', max_digits=12)),
                ('min_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Market low', max_digits=12, null=True)),
                ('max_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Market high', max_digits=12, null=True)),
                ('region', models.CharField(default='Kathmandu', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_rate_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RateRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('change_pct', models.DecimalField(decimal_places=2, max_digits=7)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='estimate.materialrate')),
                ('noted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phase_key', models.CharField(blank=True, choices=[('site_prep', 'Site Preparation & Excavation'), ('foundation', 'Foundation'), ('superstructure', 'Superstructure (Slab / Beam / Column)'), ('brickwork', 'Brickwork & Masonry'), ('roofing', 'Roofing'), ('plaster', 'Plastering'), ('flooring', 'Flooring'), ('painting', 'Painting & Finishing'), ('doors_windows', 'Doors & Windows'), ('mep', 'MEP (Electrical & Plumbing)'), ('other', 'Miscellaneous')], max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('material_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('labor_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='estimate.estimate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('MATERIAL', 'Material'), ('LABOR', 'Labor'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other')], max_length=15)),
                ('rate_key', models.CharField(blank=True, help_text='Reference to MaterialRate.key or LaborRate.trade', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit', models.CharField(max_length=20)),
                ('unit_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('wastage_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimate.estimatesection')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
