# Generated by Django 4.2.9 on 2026-04-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='rate_key',
            field=models.CharField(blank=True, help_text='Reference to MaterialRate.key or LaborRate.trade', max_length=50),
        ),
        migrations.AlterField(
            model_name='estimatesection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='laborrate',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, help_text='Rate per day in NPR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='laborrate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='materialrate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='materialrate',
            name='key',
            field=models.CharField(help_text='Canonical key used in formulas e.g. CEMENT, ROD', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='materialrate',
            name='max_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Market high', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='materialrate',
            name='min_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Market low', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='materialrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Current market price in NPR', max_digits=12),
        ),
        migrations.AlterField(
            model_name='raterevision',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
