# Generated by Django 5.2.13 on 2026-05-08 21:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contractor_name', models.CharField(help_text='Contractor / company name', max_length=255)),
                ('contract_number', models.CharField(blank=True, default='', max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_contractor_contracts', to='core.houseproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractorInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order')),
                ('milestone', models.CharField(help_text='Milestone / stage name', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(blank=True, limit_choices_to={'is_bank': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_contractor_payments', to='financials.account')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_installments', to='financials.contractorcontract')),
                ('expense_account', models.ForeignKey(blank=True, limit_choices_to={'account_type': 'EXPENSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_contractor_expenses', to='financials.account')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_contractor_installment', to='financials.journalentry')),
            ],
            options={
                'ordering': ['contract', 'order'],
            },
        ),
    ]
