# Generated by Django 5.2.13 on 2026-05-08 21:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_contractor_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractorinstallment',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='contractorinstallment',
            name='expense_account',
        ),
        migrations.RemoveField(
            model_name='contractorinstallment',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='contractorinstallment',
            name='paid_date',
        ),
        migrations.RemoveField(
            model_name='contractorinstallment',
            name='payment_reference',
        ),
        migrations.AlterField(
            model_name='contractorcontract',
            name='contractor_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contractorinstallment',
            name='milestone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contractorinstallment',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractorinstallment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(limit_choices_to={'is_bank': True}, on_delete=django.db.models.deletion.PROTECT, related_name='fin_installment_payments', to='financials.account')),
                ('expense_account', models.ForeignKey(blank=True, limit_choices_to={'account_type': 'EXPENSE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_installment_expenses', to='financials.account')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fin_payments', to='financials.contractorinstallment')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_installment_payment', to='financials.journalentry')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
