# Generated by Django 4.2.9 on 2026-05-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_installmentpayment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorcontract',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='fin/contract_documents/'),
        ),
    ]
