# Generated by Django 4.2.9 on 2026-05-18 21:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emaillog_material_switch_to_resource'),
        ('financials', '0006_vendor_phasebudgetline_budgetrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_type', models.CharField(choices=[('MATERIAL', 'Material Purchase'), ('LABOR', 'Labour / Worker Payment'), ('FEES', 'Professional Fees'), ('GOVT', 'Government / Permit Fees'), ('OTHER', 'Other Miscellaneous')], default='OTHER', max_length=20)),
                ('date', models.DateField()),
                ('paid_to', models.CharField(blank=True, default='', max_length=200)),
                ('is_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_expenses', to='core.constructionphase')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_expenses', to='core.houseproject')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
