# Generated by Django 4.2.9 on 2026-05-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_add_expense_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetcategory',
            options={'ordering': ['sequence', 'name']},
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
