# Generated by Django 4.2.9 on 2026-05-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0008_alter_budgetcategory_options_budgetcategory_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='budget_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_bill_items', to='financials.budgetcategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='budget_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fin_expenses', to='financials.budgetcategory'),
        ),
    ]
