# Generated by Django 4.2.9 on 2026-02-23 22:35

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('allocation', models.DecimalField(decimal_places=2, help_text='Allocated budget for this category', max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Budget Categories',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_type', models.CharField(choices=[('MATERIAL', 'Material Purchase'), ('LABOR', 'Labor/Worker Payment'), ('FEES', 'Professional Fees/Engineering'), ('GOVT', 'Government/Permit Fees'), ('OTHER', 'Other Miscellaneous')], default='MATERIAL', max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date', models.DateField()),
                ('paid_to', models.CharField(help_text='Vendor or person paid', max_length=200)),
                ('is_paid', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.budgetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. Nabil Bank Loan, Father's help", max_length=200)),
                ('source_type', models.CharField(choices=[('OWN_MONEY', 'Personal Savings / Own Money (Nagad/Bachat)'), ('LOAN', 'Bank Loan (Karja)'), ('BORROWED', 'Borrowed from Friends/Family (Saapathi)'), ('OTHER', 'Other Source')], default='OWN_MONEY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total allocation from this source', max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining available balance', max_digits=12)),
                ('default_payment_method', models.CharField(choices=[('CASH', 'Cash (Nagad)'), ('BANK_TRANSFER', 'Bank Transfer (ConnectIPS)'), ('CHECK', 'Cheque (Check)'), ('UPI', 'QR / Mobile Banking (eSewa/Khalti)'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Annual interest rate if applicable (%)', max_digits=5)),
                ('received_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('CASH', 'Nagad (Cash)'), ('BANK_TRANSFER', 'Bank / ConnectIPS'), ('QR', 'eSewa/Khalti/Fonepay (QR)'), ('CHECK', 'Cheque'), ('OTHER', 'Other')], max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='Check number or Transaction ID', max_length=100)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.expense')),
                ('funding_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.fundingsource')),
            ],
        ),
        migrations.CreateModel(
            name='FundingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit (Top-up/Addition)'), ('DEBIT', 'Debit (Payment/Expense)')], max_length=10)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.fundingsource')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_transactions', to='finance.payment')),
            ],
        ),
    ]
