# Generated by Django 4.2.9 on 2026-05-01 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
        ('resources', '0001_initial'),
        ('tasks', '0001_initial'),
        ('accounting', '0003_initial'),
        ('finance', '0001_initial'),
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='resources.contractor'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.constructionphase'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_purchase_orders', to='accounting.vendor'),
        ),
        migrations.AddField(
            model_name='phasebudgetallocation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_allocations', to='finance.budgetcategory'),
        ),
        migrations.AddField(
            model_name='phasebudgetallocation',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_allocations', to='core.constructionphase'),
        ),
        migrations.AddField(
            model_name='payment',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.expense'),
        ),
        migrations.AddField(
            model_name='payment',
            name='funding_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.fundingsource'),
        ),
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='finance.account'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='expense',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.expense'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='funding_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.fundingsource'),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.budgetcategory'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='contractor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resource.worker'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='funding_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.fundingsource'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='material',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resource.material'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='phase',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.constructionphase'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='receipt',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resources.document'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resource.supplier'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='fundingtransaction',
            name='funding_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.fundingsource'),
        ),
        migrations.AddField(
            model_name='fundingtransaction',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_transaction_source', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='fundingtransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_transactions', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='associated_account',
            field=models.ForeignKey(blank=True, help_text='The GL Asset account where this money is held', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_sources', to='finance.account'),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_sources', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.budgetcategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='resource.worker'),
        ),
        migrations.AddField(
            model_name='expense',
            name='funding_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.fundingsource'),
        ),
        migrations.AddField(
            model_name='expense',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='resource.material'),
        ),
        migrations.AddField(
            model_name='expense',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.constructionphase'),
        ),
        migrations.AddField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='resources.document'),
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='resource.supplier'),
        ),
        migrations.AddField(
            model_name='expense',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='associated_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_categories', to='finance.account'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_payments_made', to='finance.account'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.bill'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_payment_source', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_payments', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='finance.account'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.bill'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='finance.budgetcategory'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='resources.material'),
        ),
        migrations.AddField(
            model_name='billitem',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='core.constructionphase'),
        ),
        migrations.AddField(
            model_name='bill',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='resources.contractor'),
        ),
        migrations.AddField(
            model_name='bill',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_source', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='bill',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='bill',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='finance.purchaseorder'),
        ),
        migrations.AddField(
            model_name='bill',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_bills', to='accounting.vendor'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='finance.account'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transfer_source', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfers', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='finance.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_accounts', to='finance.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Scope this account to a specific project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.houseproject'),
        ),
        migrations.AlterUniqueTogether(
            name='phasebudgetallocation',
            unique_together={('category', 'phase')},
        ),
    ]
