# Generated by Django 4.2.9 on 2026-02-10 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_supplier_alter_contractor_rate_alter_contractor_role_and_more'),
        ('finance', '0002_expense_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='resources.contractor'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('MATERIAL', 'Material Purchase'), ('LABOR', 'Labor/Worker Payment'), ('FEES', 'Professional Fees/Engineering'), ('GOVT', 'Government/Permit Fees'), ('OTHER', 'Other Miscellaneous')], default='MATERIAL', max_length=20),
        ),
    ]
