# Generated by Django 4.2.9 on 2026-05-01 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='resource.worker'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='resource.material'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='resource.supplier'),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='contractor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resource.worker'),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='material',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resource.material'),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resource.supplier'),
        ),
    ]
