# Generated by Django 4.2.9 on 2026-05-10 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_historicalpayment_signature_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='signature_data',
            field=models.TextField(blank=True, default='', help_text='Base64 encoded signature image'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='signature_name',
            field=models.CharField(blank=True, default='', help_text='Name of person who signed', max_length=100),
        ),
    ]
