# Generated by Django 4.2.9 on 2026-02-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expense_contractor_expense_expense_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. Nabil Bank Loan, Father's help", max_length=200)),
                ('source_type', models.CharField(choices=[('OWN_MONEY', 'Own Money / Savings'), ('LOAN', 'Bank Loan'), ('BORROWED', 'Borrowed from Friends/Family'), ('OTHER', 'Other Source')], default='OWN_MONEY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount from this source', max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Annual interest rate if applicable (%)', max_digits=5)),
                ('received_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
