# Generated by Django 4.2.9 on 2026-02-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payment_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_photo',
            field=models.ImageField(blank=True, help_text='Upload proof of payment (screenshot/photo)', null=True, upload_to='payments/proofs/'),
        ),
    ]
