# Generated by Django 4.2.9 on 2026-03-03 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_payment_proof_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_inventory_usage',
            field=models.BooleanField(default=False, help_text='Represents internal cost allocation (Usage) to avoid double-counting in cashflow.'),
        ),
    ]
