# Generated by Django 4.2.9 on 2026-02-10 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_fundingsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='funding_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.fundingsource'),
        ),
    ]
