# Generated by Django 4.2.9 on 2026-05-15 01:39
# Edited: null-out old integer FK values before altering to UUID FKs.
# Old contractor_id → resources.Contractor (integer PK)
# Old material_id   → resources.Material   (integer PK)
# New FKs point at resource.Worker / resource.Material (UUID PKs) — no mapping possible.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_stockmovement_delivered_by_and_more'),
        ('finance', '0004_billpayment_signature_data_and_more'),
    ]

    operations = [
        # Step 1: clear all old integer FK values so columns can be safely
        # retyped to UUID without FK constraint violations.
        migrations.RunSQL(
            sql="""
                UPDATE finance_bill         SET contractor_id = NULL;
                UPDATE finance_billitem     SET material_id   = NULL;
                UPDATE finance_purchaseorder SET contractor_id = NULL;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Step 2: alter columns to point at resource app models (UUID PKs).
        migrations.AlterField(
            model_name='bill',
            name='contractor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='finance_bills',
                to='resource.worker',
            ),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='material',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='finance_bill_items',
                to='resource.material',
            ),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='contractor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='finance_purchase_orders',
                to='resource.worker',
            ),
        ),
    ]
