# Generated by Django 4.2.9 on 2026-05-15 01:39
# Fixed: PostgreSQL cannot cast bigint → uuid via ALTER COLUMN … USING.
# Strategy: drop each old integer FK column, re-add as a fresh uuid FK column.
# Old FKs pointed at resources.Contractor / resources.Material (integer PKs).
# New FKs point at resource.Worker / resource.Material (UUID PKs).
# No value mapping is possible, so columns are recreated nullable with no data.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_stockmovement_delivered_by_and_more'),
        ('finance', '0004_billpayment_signature_data_and_more'),
    ]

    operations = [

        # ── finance_bill.contractor_id ────────────────────────────────────────
        migrations.RunSQL(
            sql='ALTER TABLE finance_bill DROP COLUMN IF EXISTS contractor_id CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE finance_bill
                    ADD COLUMN contractor_id uuid NULL
                    REFERENCES resource_worker (id)
                    ON DELETE SET NULL
                    DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql='ALTER TABLE finance_bill DROP COLUMN IF EXISTS contractor_id CASCADE;',
        ),

        # ── finance_billitem.material_id ──────────────────────────────────────
        migrations.RunSQL(
            sql='ALTER TABLE finance_billitem DROP COLUMN IF EXISTS material_id CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE finance_billitem
                    ADD COLUMN material_id uuid NULL
                    REFERENCES resource_material (id)
                    ON DELETE SET NULL
                    DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql='ALTER TABLE finance_billitem DROP COLUMN IF EXISTS material_id CASCADE;',
        ),

        # ── finance_purchaseorder.contractor_id ───────────────────────────────
        migrations.RunSQL(
            sql='ALTER TABLE finance_purchaseorder DROP COLUMN IF EXISTS contractor_id CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE finance_purchaseorder
                    ADD COLUMN contractor_id uuid NULL
                    REFERENCES resource_worker (id)
                    ON DELETE SET NULL
                    DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql='ALTER TABLE finance_purchaseorder DROP COLUMN IF EXISTS contractor_id CASCADE;',
        ),

        # ── Update Django migration state (no SQL — already done above) ───────
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='bill',
                    name='contractor',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='finance_bills',
                        to='resource.worker',
                    ),
                ),
                migrations.AlterField(
                    model_name='billitem',
                    name='material',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='finance_bill_items',
                        to='resource.material',
                    ),
                ),
                migrations.AlterField(
                    model_name='purchaseorder',
                    name='contractor',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='finance_purchase_orders',
                        to='resource.worker',
                    ),
                ),
            ],
            database_operations=[],  # already done with RunSQL above
        ),
    ]
