# Generated by Django 4.2.9 on 2026-02-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_expense_funding_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsource',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining available balance', max_digits=12),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total allocation from this source', max_digits=12),
        ),
        migrations.CreateModel(
            name='FundingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit (Top-up/Addition)'), ('DEBIT', 'Debit (Payment/Expense)')], max_length=10)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funding_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.fundingsource')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_transactions', to='finance.payment')),
            ],
        ),
    ]
