# Generated by Django 4.2.9 on 2026-05-15 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_switch_contractor_and_material_fks_to_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='expense-documents/%Y/%m/')),
                ('document_type', models.CharField(choices=[('BILL', 'Bill/Invoice'), ('RECEIPT', 'Receipt'), ('PHOTO', 'Site Photo'), ('AGREEMENT', 'Samjhauta Patra (Contract)'), ('OTHER', 'Other')], default='RECEIPT', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.expensedocument'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='receipt',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.expensedocument'),
        ),
    ]
