# Generated by Django 4.2.9 on 2026-03-03 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0005_expense_is_inventory_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseBudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_allocations', to='finance.budgetcategory')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_allocations', to='core.constructionphase')),
            ],
            options={
                'verbose_name': 'Phase Budget Allocation',
                'verbose_name_plural': 'Phase Budget Allocations',
                'unique_together': {('category', 'phase')},
            },
        ),
    ]
