# Generated by Django 4.2.9 on 2026-02-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_fundingsource_current_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsource',
            name='default_payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('UPI', 'UPI/Digital'), ('OTHER', 'Other')], default='CASH', max_length=20),
        ),
    ]
