# Generated by Django 4.2.9 on 2026-03-10 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('finance', '0006_phasebudgetallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='tasks.task'),
        ),
    ]
