# Generated by Django 4.2.9 on 2026-02-10 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_fundingsource_default_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='funding_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.fundingsource'),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='default_payment_method',
            field=models.CharField(choices=[('CASH', 'Cash (Nagad)'), ('BANK_TRANSFER', 'Bank Transfer (ConnectIPS)'), ('CHECK', 'Cheque (Check)'), ('UPI', 'QR / Mobile Banking (eSewa/Khalti)'), ('OTHER', 'Other')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='source_type',
            field=models.CharField(choices=[('OWN_MONEY', 'Personal Savings / Own Money (Nagad/Bachat)'), ('LOAN', 'Bank Loan (Karja)'), ('BORROWED', 'Borrowed from Friends/Family (Saapathi)'), ('OTHER', 'Other Source')], default='OWN_MONEY', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash (Nagad)'), ('BANK_TRANSFER', 'Bank Transfer (ConnectIPS)'), ('CHECK', 'Cheque (Check)'), ('UPI', 'QR / Mobile Banking (eSewa/Khalti)'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
