# Generated by Django 4.2.9 on 2026-05-20 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # Must run AFTER 0010 so Django's state knows financials models use fin_* tables
        ('financials', '0010_fix_table_names'),
        ('finance', '0007_alter_bill_supplier_alter_purchaseorder_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='fin_budget_category',
            field=models.ForeignKey(blank=True, help_text='New fin.BudgetCategory this expense belongs to (for BudgetPage tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_expenses', to='financials.budgetcategory'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='fin_budget_category',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='New fin.BudgetCategory this expense belongs to (for BudgetPage tracking)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financials.budgetcategory'),
        ),
    ]
