# Generated by Django 4.2.9 on 2026-04-18 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_historicalpayment_historicalexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fundingtransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_transactions', to='finance.payment'),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
