# Generated by Django 4.2.9 on 2026-02-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_payment_funding_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Nagad (Cash)'), ('BANK_TRANSFER', 'Bank / ConnectIPS'), ('QR', 'eSewa/Khalti/Fonepay (QR)'), ('CHECK', 'Cheque'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
