# Generated by Django 4.2.9 on 2026-02-11 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_material_budget_category_and_more'),
        ('finance', '0009_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='resources.material'),
        ),
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
