# Generated by Django 4.2.9 on 2026-04-20 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_account_bill_journalentry_purchaseorder_journalline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(help_text='The account money is leaving', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='finance.account')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transfer_source', to='finance.journalentry')),
                ('to_account', models.ForeignKey(help_text='The account money is entering', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='finance.account')),
            ],
        ),
    ]
