# Generated by Django 4.2.9 on 2026-04-22 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_banktransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Specific GL account for this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='finance.account'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='associated_account',
            field=models.ForeignKey(blank=True, help_text='GL account for this budget category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_categories', to='finance.account'),
        ),
    ]
