# Generated by Django 4.2.9 on 2026-04-22 10:18

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_billitem_account_budgetcategory_associated_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='banktransfer',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-date_issued', '-id']},
        ),
        migrations.AlterModelOptions(
            name='billpayment',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='budgetcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Budget Categories'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='fundingtransaction',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='associated_account',
            field=models.ForeignKey(blank=True, help_text='The GL Asset account where this money is held', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_sources', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_items', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='billpayment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_payments_made', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='allocation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='associated_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_categories', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('MATERIAL', 'Material Purchase'), ('LABOR', 'Labor/Worker Payment'), ('FEES', 'Professional Fees'), ('GOVT', 'Government/Permit Fees'), ('OTHER', 'Other Miscellaneous')], default='MATERIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_inventory_usage',
            field=models.BooleanField(default=False, help_text='Internal cost allocation — excluded from cashflow to avoid double counting.'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_to',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total allocated capital', max_digits=12),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='default_payment_method',
            field=models.CharField(choices=[('CASH', 'Cash (Nagad)'), ('BANK_TRANSFER', 'Bank Transfer (ConnectIPS)'), ('CHECK', 'Cheque'), ('UPI', 'QR / Mobile Banking'), ('OTHER', 'Other')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fundingtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='expense_type',
            field=models.CharField(choices=[('MATERIAL', 'Material Purchase'), ('LABOR', 'Labor/Worker Payment'), ('FEES', 'Professional Fees'), ('GOVT', 'Government/Permit Fees'), ('OTHER', 'Other Miscellaneous')], default='MATERIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='is_inventory_usage',
            field=models.BooleanField(default=False, help_text='Internal cost allocation — excluded from cashflow to avoid double counting.'),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='paid_to',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Nagad (Cash)'), ('BANK_TRANSFER', 'Bank / ConnectIPS'), ('QR', 'eSewa/Khalti/Fonepay'), ('CHECK', 'Cheque'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='proof_photo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('BILL', 'Vendor Bill'), ('PAYMENT', 'Bill Payment'), ('INVOICE', 'Client Invoice'), ('RECEIPT', 'Payment Received'), ('MANUAL', 'Manual Journal Entry'), ('INITIAL', 'Opening Balance'), ('TRANSFER', 'Bank Transfer'), ('EXPENSE', 'Direct Expense'), ('FUNDING', 'Funding Received')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='entry_type',
            field=models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Nagad (Cash)'), ('BANK_TRANSFER', 'Bank / ConnectIPS'), ('QR', 'eSewa/Khalti/Fonepay'), ('CHECK', 'Cheque'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='proof_photo',
            field=models.ImageField(blank=True, null=True, upload_to='payments/proofs/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
