# Generated by Django 4.2.9 on 2026-04-22 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_account_options_alter_banktransfer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingtransaction',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_transaction_source', to='finance.journalentry'),
        ),
    ]
