# Generated by Django 4.2.9 on 2026-04-23 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_vendor_account_number_vendor_bank_name_vendor_branch_and_more'),
        ('finance', '0014_fundingtransaction_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_v', to='accounting.vendor'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='vendor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.vendor'),
        ),
    ]
