# Generated by Django 4.2.9 on 2026-04-23 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_merge_suppliers'),
        ('finance', '0015_expense_vendor_historicalexpense_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='historicalexpense',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='supplier',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='vendor',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='historicalexpense',
            old_name='vendor',
            new_name='supplier',
        ),
        migrations.AddField(
            model_name='bill',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_bills', to='accounting.vendor'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_purchase_orders', to='accounting.vendor'),
        ),
    ]
