# Generated by Django 4.2.9 on 2026-04-23 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_room_polygon_points'),
        ('accounting', '0007_merge_suppliers'),
        ('finance', '0016_remove_expense_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Scope this account to a specific project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfers', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='bill',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_sources', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.houseproject'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounting.vendor'),
        ),
    ]
