# Generated by Django 4.2.9 on 2026-04-23 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_room_polygon_points'),
        ('finance', '0017_account_project_banktransfer_project_bill_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.houseproject'),
        ),
    ]
