# Generated by Django 4.2.9 on 2026-04-23 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_floor_project'),
        ('finance', '0018_historicalpayment_project_payment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_payments', to='core.houseproject'),
        ),
    ]
