# Generated by Django 4.2.9 on 2026-05-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_projects',
            field=models.ManyToManyField(blank=True, help_text='Projects this user is allowed to access', related_name='assigned_users', to='core.houseproject'),
        ),
    ]
