# Generated by Django 4.2.9 on 2026-03-02 01:22

import apps.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Backup username in case user is deleted', max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('VIEW', 'Viewed'), ('LOGIN', 'Logged In'), ('LOGOUT', 'Logged Out'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('PAY', 'Paid')], db_index=True, help_text='Type of action performed', max_length=20)),
                ('model_name', models.CharField(db_index=True, help_text='Name of the model affected (e.g., Expense, Phase)', max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='ID of the object affected', max_length=100, null=True)),
                ('object_repr', models.CharField(help_text='Human-readable representation of the object', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action')),
                ('changes', models.JSONField(blank=True, help_text='Before/after values for updates', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string from the request')),
                ('endpoint', models.CharField(blank=True, help_text='API endpoint called', max_length=500)),
                ('method', models.CharField(blank=True, help_text='HTTP method (GET, POST, PUT, DELETE)', max_length=10)),
                ('success', models.BooleanField(default=True, help_text='Whether the action completed successfully')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('HOME_OWNER', 'Home Owner'), ('LEAD_ENGINEER', 'Lead Engineer'), ('CONTRACTOR', 'Contractor'), ('VIEWER', 'Viewer')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('can_manage_all_systems', models.BooleanField(default=False, help_text='Full system access - can manage all data')),
                ('can_manage_finances', models.BooleanField(default=False, help_text='Can manage expenses, budgets, and payments')),
                ('can_view_finances', models.BooleanField(default=False, help_text='Can view expenses, budgets, and payments')),
                ('can_manage_phases', models.BooleanField(default=False, help_text='Can manage construction phases and tasks')),
                ('can_view_phases', models.BooleanField(default=True, help_text='Can view construction phases')),
                ('can_manage_users', models.BooleanField(default=False, help_text='Can manage users and roles')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='frontend_last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.user_profile_image_path),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-timestamp', 'user'], name='accounts_ac_timesta_df1272_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['model_name', '-timestamp'], name='accounts_ac_model_n_d70c39_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', '-timestamp'], name='accounts_ac_action_448a74_idx'),
        ),
    ]
