# Generated by Django 4.2.9 on 2026-03-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activitylog_role_alter_user_options_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='typography_settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
