# Generated by Django 4.2.9 on 2026-04-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_typography_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
