# Generated by Django 4.2.9 on 2026-05-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_active_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_structure',
            field=models.BooleanField(default=False, help_text='Can manage floors and rooms'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_structure',
            field=models.BooleanField(default=True, help_text='Can view floors and rooms'),
        ),
    ]
