# Generated by Django 4.2.9 on 2026-04-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_floor_project'),
        ('accounts', '0004_activitylog_city_activitylog_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_projects',
            field=models.ManyToManyField(blank=True, help_text='Projects this user is allowed to access', related_name='assigned_users', to='core.houseproject'),
        ),
    ]
