# Generated by Django 4.2.9 on 2026-05-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role_can_manage_structure_role_can_view_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='digital_signature',
            field=models.TextField(blank=True, default='', help_text='Base64 encoded digital signature image'),
        ),
    ]
