# Generated by Django 4.2.9 on 2026-05-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_allow_custom_role_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_manage_admin_config',
            field=models.BooleanField(default=False, help_text='Can manage users, roles, and other admin configuration pages'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_profile',
            field=models.BooleanField(default=True, help_text='Can view the personal profile page'),
        ),
    ]
