# Generated by Django 5.2.13 on 2026-05-14 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('workforce', '0001_initial'),
    ]

    operations = [
        # Clear stale contractor IDs before changing the FK target.
        # Old assigned_to_id was an integer referencing resources.Contractor;
        # the new target is workforce.WorkforceMember (UUID PK), so any
        # existing integer value would violate the FK constraint.
        migrations.RunSQL(
            sql="UPDATE tasks_task SET assigned_to_id = NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workforce.workforcemember'),
        ),
    ]
