# Generated by Django 4.2.9 on 2026-03-10 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_expense_task'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Finance category this task belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='finance.budgetcategory'),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Budgeted cost for this specific task', max_digits=12),
        ),
    ]
