# Generated by Django 5.2.13 on 2026-05-14 09:38
# Fixed: PostgreSQL cannot cast bigint → uuid via ALTER COLUMN … USING.
# Strategy: drop old integer FK column, re-add as fresh uuid FK column.
# Old assigned_to_id → resources.Contractor (integer PK).
# New assigned_to_id → workforce.WorkforceMember (UUID PK). No value mapping.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('workforce', '0001_initial'),
    ]

    operations = [
        # Drop old bigint assigned_to_id (CASCADE removes FK constraint).
        migrations.RunSQL(
            sql='ALTER TABLE tasks_task DROP COLUMN IF EXISTS assigned_to_id CASCADE;',
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Re-add as uuid FK referencing workforce.WorkforceMember.
        migrations.RunSQL(
            sql="""
                ALTER TABLE tasks_task
                    ADD COLUMN assigned_to_id uuid NULL
                    REFERENCES workforce_workforcemember (id)
                    ON DELETE SET NULL
                    DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql='ALTER TABLE tasks_task DROP COLUMN IF EXISTS assigned_to_id CASCADE;',
        ),

        # Update Django migration state only — SQL already done above.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='task',
                    name='assigned_to',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='tasks',
                        to='workforce.workforcemember',
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
