# Generated by Django 4.2.9 on 2026-05-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='technical_requirement',
            field=models.TextField(blank=True, help_text='Specific technical steps or requirements for this task'),
        ),
    ]
