# Generated by Django 4.2.9 on 2026-03-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_category_task_estimated_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmedia',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], default='IMAGE', max_length=10),
        ),
    ]
