# Generated by Django 4.2.9 on 2026-03-31 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskmedia_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blocked_by',
            field=models.ForeignKey(blank=True, help_text='This task cannot be completed until the blocked_by task is completed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocking_tasks', to='tasks.task'),
        ),
    ]
