# Generated by Django 4.2.9 on 2026-05-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='task-documents/%Y/%m/')),
                ('document_type', models.CharField(choices=[('IMAGE', 'Image / Photo'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document / PDF'), ('OTHER', 'Other')], default='DOCUMENT', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='taskupdate',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='task_updates', to='tasks.taskdocument'),
        ),
    ]
