# Generated by Django 4.2.9 on 2026-05-19 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_add_taskdocument_own_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmedia',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='tasks.task'),
        ),
    ]
