# Generated by Django 4.2.9 on 2026-05-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_make_taskmedia_task_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmedia',
            name='telegram_uploader_name',
            field=models.CharField(blank=True, help_text='Name of the Telegram user who uploaded this media', max_length=150, null=True),
        ),
    ]
