# Generated by Django 4.2.9 on 2026-06-12 09:01

from django.db import migrations, models
import django.db.models.deletion


def backfill_taskmedia_project(apps, schema_editor):
    TaskMedia = apps.get_model('tasks', 'TaskMedia')
    HouseProject = apps.get_model('core', 'HouseProject')

    for media in TaskMedia.objects.select_related('task__phase__project').filter(project__isnull=True, task__isnull=False):
        project_id = media.task.phase.project_id if media.task and media.task.phase_id else None
        if project_id:
            TaskMedia.objects.filter(pk=media.pk).update(project_id=project_id)

    projects = list(HouseProject.objects.values_list('id', flat=True)[:2])
    if len(projects) == 1:
        TaskMedia.objects.filter(project__isnull=True, task__isnull=True).update(project_id=projects[0])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_project_role_view_permissions'),
        ('tasks', '0007_taskmedia_telegram_uploader_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmedia',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project scope for unassigned/general uploads.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_media', to='core.houseproject'),
        ),
        migrations.RunPython(backfill_taskmedia_project, migrations.RunPython.noop),
    ]
