# Generated by Django 4.2.9 on 2026-05-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, help_text='The API Token from @BotFather', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Whether the bot integration is active')),
                ('webhook_url', models.URLField(blank=True, help_text='The URL registered with Telegram for webhooks', max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Settings',
                'verbose_name_plural': 'Telegram Settings',
            },
        ),
    ]
