# Generated by Django 4.2.9 on 2026-05-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsettings',
            name='notification_chat_id',
            field=models.CharField(blank=True, help_text='The Telegram Chat ID to send notifications to', max_length=50, null=True),
        ),
    ]
