# Generated by Django 4.2.9 on 2026-04-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workforcemember',
            name='portal_pin',
            field=models.CharField(blank=True, help_text='Plaintext PIN for the worker portal. Visible to admins.', max_length=10),
        ),
    ]
