# Generated by Django 4.2.9 on 2026-05-01 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0002_workforcemember_portal_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workforcemember',
            name='portal_pin',
        ),
    ]
