# Generated by Django 4.2.9 on 2026-05-01 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('tasks', '0001_initial'),
        ('workforce', '0003_remove_workforcemember_portal_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerassignment',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workerassignment',
            name='estimated_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workerassignment',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_assignments', to='core.constructionphase'),
        ),
        migrations.AddField(
            model_name='workerassignment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_assignments', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='workerassignment',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total overtime hours pulled from DailyAttendance records.', max_digits=10),
        ),
    ]
