# Generated by Django 4.2.9 on 2026-05-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paused', models.BooleanField(default=False)),
                ('schedule_expression', models.CharField(default='0 2 * * *', help_text='Cron expression for automated backups', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Backup Settings',
            },
        ),
        migrations.AddField(
            model_name='backuplog',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
