# Generated by Django 4.2.9 on 2026-05-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0002_backupsettings_backuplog_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupsettings',
            name='gdrive_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='gdrive_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='gdrive_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='backupsettings',
            name='gdrive_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
