# Generated by Django 4.2.9 on 2026-05-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0003_backupsettings_gdrive_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuplog',
            name='current_stage',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='backuplog',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
    ]
