# Generated by Django 4.2.9 on 2026-04-29 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('TODO', 'To Do'), ('GATHERING', 'Gathering Docs'), ('SUBMITTED', 'Submitted'), ('DONE', 'Done'), ('BLOCKED', 'Blocked')], default='TODO', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('fee_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permit_items', to=settings.AUTH_USER_MODEL)),
                ('attached_documents', models.ManyToManyField(blank=True, related_name='permit_items', to='resources.document')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('LAND', 'Land Ownership'), ('ID', 'Citizenship/ID'), ('DRAWING', 'Drawings / Naksha'), ('APPROVAL', 'Approval / Endorsement'), ('FEE', 'Fee Receipt'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('sample_file', models.FileField(blank=True, null=True, upload_to='permit-samples/')),
                ('source_hint', models.CharField(blank=True, help_text="Where to get this — e.g. 'Malpot Karyalaya'", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('municipality', models.CharField(max_length=200)),
                ('ward', models.CharField(blank=True, max_length=20)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['municipality', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PermitStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('documents', models.ManyToManyField(blank=True, help_text='Documents required/submitted for this permit step', related_name='permit_steps', to='resources.document')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permit_steps', to='core.houseproject')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PermitChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('target_completion', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_checklists', to='core.houseproject')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='permits.municipalitytemplate')),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalityStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('typical_days', models.PositiveIntegerField(default=7, help_text='SLA hint')),
                ('fee_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('required_documents', models.ManyToManyField(blank=True, related_name='steps', to='permits.documenttemplate')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='permits.municipalitytemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeadlineReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_on', models.DateField()),
                ('message', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('SENT', 'Sent'), ('OVERDUE', 'Overdue'), ('CLEARED', 'Cleared')], default='SCHEDULED', max_length=15)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='permits.checklistitem')),
            ],
            options={
                'ordering': ['remind_on'],
            },
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='permits.permitchecklist'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='source_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='permits.municipalitystep'),
        ),
    ]
