# Generated by Django 4.2.9 on 2026-02-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_materialtransaction_create_expense'),
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitstep',
            name='documents',
            field=models.ManyToManyField(blank=True, help_text='Documents required/submitted for this permit step', related_name='permit_steps', to='resources.document'),
        ),
    ]
