# Generated by Django 4.2.9 on 2026-03-31 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegalDocument',
        ),
    ]
