# Generated by Django 4.2.9 on 2026-05-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='permit-documents/%Y/%m/')),
                ('document_type', models.CharField(choices=[('NAKSHA', 'Naksha (Blueprint/Map)'), ('LALPURJA', 'Lalpurja (Land Cert)'), ('NAGRIKTA', 'Nagrikta (Citizenship)'), ('TIRO', 'Tiro Rasid (Tax Receipt)'), ('CHARKILLA', 'Charkilla (Boundary)'), ('PERMIT', 'Nagar Palika Permit'), ('BILL', 'Bill/Invoice'), ('PHOTO', 'Site Photo'), ('AGREEMENT', 'Samjhauta Patra (Contract)'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='attached_documents',
            field=models.ManyToManyField(blank=True, related_name='permit_items', to='permits.permitdocument'),
        ),
        migrations.AlterField(
            model_name='permitstep',
            name='documents',
            field=models.ManyToManyField(blank=True, help_text='Documents required/submitted for this permit step', related_name='permit_steps', to='permits.permitdocument'),
        ),
    ]
