# Generated by Django 4.2.9 on 2026-04-23 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_floor_project'),
        ('permits', '0003_checklistitem_documenttemplate_municipalitytemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permitstep',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permit_steps', to='core.houseproject'),
        ),
    ]
