# Generated by Django 4.2.9 on 2026-02-23 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('THEKEDAAR', 'Thekedaar (Contractor)'), ('ENGINEER', 'Civil Engineer'), ('MISTRI', 'Mistri (Mason)'), ('LABOUR', 'Labour (Helper)'), ('ELECTRICIAN', 'Electrician'), ('PLUMBER', 'Plumber'), ('CARPENTER', 'Carpenter/Kaath Mistri'), ('PAINTER', 'Painter'), ('TILE_MISTRI', 'Tile/Marble Mistri'), ('WELDER', 'Welder/Grill Mistri'), ('OTHER', 'Other')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('citizenship_number', models.CharField(blank=True, max_length=50)),
                ('bank_details', models.TextField(blank=True, help_text='Bank, Account No, Branch')),
                ('skills', models.TextField(blank=True, help_text='Comma separated skills')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Daily Wages or Contract Amount', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('document_type', models.CharField(choices=[('NAKSHA', 'Naksha (Blueprint/Map)'), ('LALPURJA', 'Lalpurja (Land Cert)'), ('PERMIT', 'Nagar Palika Permit'), ('BILL', 'Bill/Invoice'), ('PHOTO', 'Site Photo'), ('AGREEMENT', 'Samjhauta Patra (Contract)'), ('OTHER', 'Other')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., OPC Cement, Baluwa (Sand), Gitti (Aggregates)', max_length=100)),
                ('category', models.CharField(blank=True, help_text='e.g., Civil, Plumbing, Electrical', max_length=50)),
                ('unit', models.CharField(choices=[('TIPPER', 'Tipper'), ('TRACTOR', 'Tractor'), ('BORA', 'Bora (Sack)'), ('BUNDLE', 'Bundle'), ('PCS', 'Pieces'), ('KG', 'Kilograms (Kg)'), ('TON', 'Ton'), ('LITER', 'Liter'), ('SQFT', 'Sq. Ft.'), ('CFT', 'Cu. Ft.'), ('TRUCK', 'Truck Load')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/')),
                ('quantity_estimated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_purchased', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=0, help_text='Alert level', max_digits=10)),
                ('avg_cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='finance.budgetcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('category', models.CharField(help_text='e.g., Civil Materials, Electrical, Plumbing', max_length=100)),
                ('pan_number', models.CharField(blank=True, max_length=20, verbose_name='PAN/VAT Number')),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In (Purchase)'), ('OUT', 'Stock Out (Used)'), ('RETURN', 'Supplier Return'), ('WASTAGE', 'Wastage/Loss')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Order'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('purpose', models.CharField(blank=True, help_text='e.g., Ground Floor Slab, Kitchen Walls', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('create_expense', models.BooleanField(default=True, help_text='Uncheck for Opening Stock or Gifts (No Expense created)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='finance.expense')),
                ('funding_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='finance.fundingsource')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='resources.material')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_usage', to='core.room')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='resources.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='resources.supplier'),
        ),
    ]
