# Generated by Django 4.2.9 on 2026-05-01 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('document_type', models.CharField(choices=[('NAKSHA', 'Naksha (Blueprint/Map)'), ('LALPURJA', 'Lalpurja (Land Cert)'), ('NAGRIKTA', 'Nagrikta (Citizenship)'), ('TIRO', 'Tiro Rasid (Tax Receipt)'), ('CHARKILLA', 'Charkilla (Boundary)'), ('PERMIT', 'Nagar Palika Permit'), ('BILL', 'Bill/Invoice'), ('PHOTO', 'Site Photo'), ('AGREEMENT', 'Samjhauta Patra (Contract)'), ('OTHER', 'Other')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., OPC Cement, Baluwa (Sand), Gitti (Aggregates)', max_length=100)),
                ('category', models.CharField(blank=True, help_text='e.g., Civil, Plumbing, Electrical', max_length=50)),
                ('unit', models.CharField(choices=[('TIPPER', 'Tipper'), ('TRACTOR', 'Tractor'), ('BORA', 'Bora (Sack)'), ('BUNDLE', 'Bundle'), ('PCS', 'Pieces'), ('KG', 'Kilograms (Kg)'), ('TON', 'Ton'), ('LITER', 'Liter'), ('SQFT', 'Sq. Ft.'), ('CFT', 'Cu. Ft.'), ('TRUCK', 'Truck Load')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/')),
                ('quantity_estimated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_purchased', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_wasted', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=0, help_text='General alert level', max_digits=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, help_text='Critical level to trigger reorder warning', max_digits=10)),
                ('avg_cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='finance.budgetcategory')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.houseproject')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='accounting.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In (Purchase)'), ('OUT', 'Stock Out (Used)'), ('RETURN', 'Supplier Return'), ('WASTAGE', 'Wastage/Loss')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Order'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('purpose', models.CharField(blank=True, help_text='e.g., Ground Floor Slab, Kitchen Walls', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('create_expense', models.BooleanField(default=True, help_text='Uncheck for Opening Stock or Gifts (No Expense created)')),
                ('receipt_image', models.ImageField(blank=True, help_text='Photo of challan/bill for this stock entry', null=True, upload_to='stock-receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='finance.expense')),
                ('funding_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='finance.fundingsource')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='resources.material')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_usage', to='core.constructionphase')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_usage', to='core.room')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='accounting.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='WastageThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_pct', models.FloatField(default=8.0)),
                ('critical_pct', models.FloatField(default=15.0)),
                ('notify_owner', models.BooleanField(default=True)),
                ('notify_engineer', models.BooleanField(default=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='resources.material')),
            ],
        ),
        migrations.CreateModel(
            name='WastageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=10)),
                ('wastage_pct', models.FloatField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='resources.material')),
                ('threshold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.wastagethreshold')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.materialtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('THEKEDAAR', 'Thekedaar (Contractor)'), ('ENGINEER', 'Civil Engineer'), ('MISTRI', 'Mistri (Mason)'), ('LABOUR', 'Labour (Helper)'), ('ELECTRICIAN', 'Electrician'), ('PLUMBER', 'Plumber'), ('CARPENTER', 'Carpenter/Kaath Mistri'), ('PAINTER', 'Painter'), ('TILE_MISTRI', 'Tile/Marble Mistri'), ('WELDER', 'Welder/Grill Mistri'), ('OTHER', 'Other')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='contractors/')),
                ('citizenship_number', models.CharField(blank=True, max_length=50)),
                ('bank_details', models.TextField(blank=True, help_text='Bank, Account No, Branch')),
                ('skills', models.TextField(blank=True, help_text='Comma separated skills')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Contract Amount', max_digits=10, null=True)),
                ('daily_wage', models.DecimalField(blank=True, decimal_places=2, help_text='Daily Wage (Jyaala) for laborers', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='core.houseproject')),
                ('user', models.OneToOneField(blank=True, help_text='Linked user account for this contractor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
