# Generated by Django 4.2.9 on 2026-02-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('ARCHITECT', 'Architect'), ('ENGINEER', 'Civil Engineer'), ('MASON', 'Mason/Bricklayer'), ('ELECTRICIAN', 'Electrician'), ('PLUMBER', 'Plumber'), ('CARPENTER', 'Carpenter'), ('PAINTER', 'Painter'), ('LABORER', 'General Laborer'), ('OTHER', 'Other')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rate per day or contract amount', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('document_type', models.CharField(choices=[('BLUEPRINT', 'Blueprint/Plan'), ('PERMIT', 'Legal Permit'), ('INVOICE', 'Bill/Invoice'), ('PHOTO', 'Site Photo'), ('CONTRACT', 'Contract/Agreement'), ('OTHER', 'Other')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Ultratech Cement, Red Bricks', max_length=100)),
                ('category', models.CharField(blank=True, help_text='e.g., Structural, Finishing, Electrical', max_length=50)),
                ('unit', models.CharField(choices=[('BAG', 'Bags'), ('KG', 'Kilograms'), ('TON', 'Tons'), ('PCS', 'Pieces'), ('SQFT', 'Square Feet'), ('CFT', 'Cubic Feet'), ('LITER', 'Liters'), ('TRUCK', 'Truck Load'), ('OTHER', 'Other')], max_length=10)),
                ('quantity_estimated', models.DecimalField(decimal_places=2, default=0, help_text='Total estimated requirement', max_digits=10)),
                ('quantity_purchased', models.DecimalField(decimal_places=2, default=0, help_text='Total purchased so far', max_digits=10)),
                ('quantity_used', models.DecimalField(decimal_places=2, default=0, help_text='Consumed in construction', max_digits=10)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
