# Generated by Django 4.2.9 on 2026-02-10 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('category', models.CharField(help_text='e.g., Civil Materials, Electrical, Plumbing', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contractor',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily Wages or Contract Amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='role',
            field=models.CharField(choices=[('THEKEDAAR', 'Thekedaar (Contractor)'), ('ENGINEER', 'Civil Engineer'), ('MISTRI', 'Mistri (Mason)'), ('LABOUR', 'Labour (Helper)'), ('ELECTRICIAN', 'Electrician'), ('PLUMBER', 'Plumber'), ('CARPENTER', 'Carpenter/Kaath Mistri'), ('PAINTER', 'Painter'), ('TILE_MISTRI', 'Tile/Marble Mistri'), ('WELDER', 'Welder/Grill Mistri'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('NAKSHA', 'Naksha (Blueprint/Map)'), ('LALPURJA', 'Lalpurja (Land Cert)'), ('PERMIT', 'Nagar Palika Permit'), ('BILL', 'Bill/Invoice'), ('PHOTO', 'Site Photo'), ('AGREEMENT', 'Samjhauta Patra (Contract)'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(blank=True, help_text='e.g., Civil, Plumbing, Electrical', max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(help_text='e.g., OPC Cement, Baluwa (Sand), Gitti (Aggregates)', max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity_estimated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity_purchased',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='quantity_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('TIPPER', 'Tipper'), ('TRACTOR', 'Tractor'), ('BORA', 'Bora (Sack)'), ('BUNDLE', 'Bundle'), ('PCS', 'Pieces'), ('KG', 'Kilograms (Kg)'), ('TON', 'Ton'), ('LITER', 'Liter'), ('SQFT', 'Sq. Ft.'), ('CFT', 'Cu. Ft.'), ('TRUCK', 'Truck Load')], max_length=10),
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='resources.supplier'),
        ),
    ]
