# Generated by Django 4.2.9 on 2026-02-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contractors/'),
        ),
    ]
