# Generated by Django 4.2.9 on 2026-02-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_contractor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
