# Generated by Django 4.2.9 on 2026-02-10 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_floor_alter_constructionphase_name_and_more'),
        ('finance', '0003_expense_contractor_expense_expense_type'),
        ('resources', '0002_supplier_alter_contractor_rate_alter_contractor_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='reorder_level',
        ),
        migrations.AddField(
            model_name='contractor',
            name='bank_details',
            field=models.TextField(blank=True, help_text='Bank, Account No, Branch'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='citizenship_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contractor',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma separated skills'),
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/'),
        ),
        migrations.AddField(
            model_name='material',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Alert level', max_digits=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='PAN/VAT Number'),
        ),
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In (Purchase)'), ('OUT', 'Stock Out (Used)'), ('RETURN', 'Supplier Return'), ('WASTAGE', 'Wastage/Loss')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='finance.expense')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='resources.material')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_usage', to='core.room')),
            ],
        ),
    ]
