# Generated by Django 4.2.9 on 2026-02-10 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_remove_material_reorder_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtransaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='resources.supplier'),
        ),
    ]
