# Generated by Django 4.2.9 on 2026-02-10 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_expense_funding_source'),
        ('resources', '0004_materialtransaction_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='budget_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='finance.budgetcategory'),
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='funding_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='finance.fundingsource'),
        ),
    ]
