# Generated by Django 4.2.9 on 2026-03-02 03:34

from django.db import migrations
from django.utils.text import slugify

def link_contractors_to_users(apps, schema_editor):
    Contractor = apps.get_model('resources', 'Contractor')
    User = apps.get_model('accounts', 'User')
    Role = apps.get_model('accounts', 'Role')

    try:
        contractor_role = Role.objects.get(code='CONTRACTOR')
    except Role.DoesNotExist:
        # Fallback if roles aren't initialized yet
        contractor_role = Role.objects.create(code='CONTRACTOR', name='Contractor')

    for contractor in Contractor.objects.all():
        if contractor.user:
            continue
        
        email = contractor.email
        if not email:
            # Generate dummy email if missing
            email = f"{slugify(contractor.name)}@example.com"
        
        # Try to find user by email
        user = User.objects.filter(email=email).first()
        
        if not user:
            # Create user if not exists
            username = slugify(contractor.name).replace('-', '_')
            # Ensure unique username
            base_username = username
            counter = 1
            while User.objects.filter(username=username).exists():
                username = f"{base_username}_{counter}"
                counter += 1
            
            # Split name for first/last
            name_parts = contractor.name.split(' ', 1)
            first_name = name_parts[0]
            last_name = name_parts[1] if len(name_parts) > 1 else ''

            user = User.objects.create_user(
                username=username,
                email=email,
                password='password123', # Default password for migration
                first_name=first_name,
                last_name=last_name,
                role=contractor_role
            )
            print(f"Created user {username} for contractor {contractor.name}")
        
        contractor.user = user
        contractor.save()

def reverse_link(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_contractor_user'),
        ('accounts', '0002_activitylog_role_alter_user_options_user_address_and_more'),
    ]

    operations = [
        migrations.RunPython(link_contractors_to_users, reverse_link),
    ]
