# Generated by Django 4.2.9 on 2026-02-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_material_budget_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtransaction',
            name='purpose',
            field=models.CharField(blank=True, help_text='e.g., Ground Floor Slab, Kitchen Walls', max_length=200),
        ),
    ]
