# Generated by Django 4.2.9 on 2026-03-03 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('resources', '0005_link_contractors_to_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtransaction',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_usage', to='core.constructionphase'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
