# Generated by Django 4.2.9 on 2026-02-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_materialtransaction_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtransaction',
            name='create_expense',
            field=models.BooleanField(default=True, help_text='Uncheck for Opening Stock or Gifts (No Expense created)'),
        ),
    ]
