# Generated by Django 4.2.9 on 2026-03-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_materialtransaction_phase_alter_contractor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='daily_wage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily Wage (Jyaala) for laborers', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Critical level to trigger reorder warning', max_digits=10),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contract Amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('NAKSHA', 'Naksha (Blueprint/Map)'), ('LALPURJA', 'Lalpurja (Land Cert)'), ('NAGRIKTA', 'Nagrikta (Citizenship)'), ('TIRO', 'Tiro Rasid (Tax Receipt)'), ('CHARKILLA', 'Charkilla (Boundary)'), ('PERMIT', 'Nagar Palika Permit'), ('BILL', 'Bill/Invoice'), ('PHOTO', 'Site Photo'), ('AGREEMENT', 'Samjhauta Patra (Contract)'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='min_stock_level',
            field=models.DecimalField(decimal_places=2, default=0, help_text='General alert level', max_digits=10),
        ),
    ]
