# Generated by Django 4.2.9 on 2026-04-03 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_contractor_daily_wage_material_reorder_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='total_wasted',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='WastageThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_pct', models.FloatField(default=8.0)),
                ('critical_pct', models.FloatField(default=15.0)),
                ('notify_owner', models.BooleanField(default=True)),
                ('notify_engineer', models.BooleanField(default=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='resources.material')),
            ],
        ),
        migrations.CreateModel(
            name='WastageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=10)),
                ('wastage_pct', models.FloatField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='resources.material')),
                ('threshold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.wastagethreshold')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.materialtransaction')),
            ],
        ),
    ]
