# Generated by Django 4.2.9 on 2026-02-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_materialtransaction_create_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Order'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='RECEIVED', max_length=20),
        ),
    ]
