# Generated by Django 4.2.9 on 2026-04-23 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_vendor_account_number_vendor_bank_name_vendor_branch_and_more'),
        ('resources', '0009_materialtransaction_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials_v', to='accounting.vendor'),
        ),
        migrations.AddField(
            model_name='materialtransaction',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions_v', to='accounting.vendor'),
        ),
    ]
