# Generated by Django 4.2.9 on 2026-04-23 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_merge_suppliers'),
        ('finance', '0016_remove_expense_vendor_and_more'),
        ('analytics', '0002_alter_supplierratetrend_supplier'),
        ('resources', '0010_material_vendor_materialtransaction_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='materialtransaction',
            name='supplier',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='vendor',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='materialtransaction',
            old_name='vendor',
            new_name='supplier',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
