# Generated by Django 4.2.9 on 2026-04-23 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_merge_suppliers'),
        ('resources', '0011_remove_material_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='accounting.vendor'),
        ),
        migrations.AlterField(
            model_name='materialtransaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='accounting.vendor'),
        ),
    ]
