# Generated by Django 4.2.9 on 2026-04-23 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_room_polygon_points'),
        ('resources', '0012_alter_material_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='material',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.houseproject'),
        ),
    ]
