# Generated by Django 4.2.9 on 2026-02-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The unique key used in calculation services (e.g., CEMENT, SAND)', max_length=50, unique=True)),
                ('label', models.CharField(help_text='Display name for the rate', max_length=100)),
                ('value', models.DecimalField(decimal_places=2, help_text='Price per unit in NPR', max_digits=12)),
                ('unit', models.CharField(help_text='Unit of measurement (e.g., Bag, Cft, Kg, Sq.Ft)', max_length=20)),
                ('category', models.CharField(choices=[('MATERIAL', 'Material'), ('LABOR', 'Labor'), ('OTHER', 'Other')], default='MATERIAL', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'label'],
            },
        ),
    ]
