# Generated by Django 4.2.9 on 2026-04-22 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emaillog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoQTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quality_tier', models.CharField(choices=[('BUDGET', 'Budget'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='STANDARD', max_length=10)),
                ('min_sqft', models.PositiveIntegerField(default=0)),
                ('max_sqft', models.PositiveIntegerField(default=0, help_text='0 = unbounded')),
                ('storeys_applicable', models.CharField(blank=True, help_text="Comma-separated list e.g. '1,2,3' — empty means any", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['quality_tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedBoQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.JSONField(default=dict)),
                ('material_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('labor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('equipment_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_applied_to_budget', models.BooleanField(default=False, help_text='True once BudgetCategory rows have been auto-created/updated.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_boqs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_boqs', to='core.houseproject')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_boqs', to='estimator.boqtemplate')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedBoQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_key', models.CharField(blank=True, max_length=40)),
                ('label', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('rate_key', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('unit_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('waste_pct', models.FloatField(default=0.0)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimator.generatedboq')),
            ],
            options={
                'ordering': ['phase_key', 'label'],
            },
        ),
        migrations.CreateModel(
            name='BoQTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_key', models.CharField(help_text="Canonical phase key (e.g. 'foundation', 'slab_dhalaan')", max_length=40)),
                ('label', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('MATERIAL', 'Material'), ('LABOR', 'Labor'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other')], max_length=20)),
                ('rate_key', models.CharField(help_text="Points at ConstructionRate.key (e.g. 'CEMENT', 'SAND')", max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('quantity_formula', models.CharField(help_text="Arithmetic formula over variables — e.g. '0.4 * total_sqft'", max_length=200)),
                ('waste_pct', models.FloatField(default=5.0, help_text='Default waste factor')),
                ('notes', models.TextField(blank=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='estimator.boqtemplate')),
            ],
            options={
                'ordering': ['phase_key', 'label'],
            },
        ),
    ]
