# Generated by Django 4.2.9 on 2026-05-28 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFaceSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.TextField(help_text='JSON serialized 128-dimensional face embedding vector.')),
                ('training_samples_count', models.IntegerField(default=1, help_text='Number of samples consolidated to build this biometric profile.')),
                ('image_quality_score', models.FloatField(default=1.0, help_text='Average score rating of processed facial training frames.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_signature', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Face Signature',
                'verbose_name_plural': 'User Face Signatures',
                'db_table': 'biometrics_user_face_signature',
            },
        ),
    ]
