# Generated by Django 4.2.9 on 2026-04-29 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timelapse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scope', models.CharField(choices=[('ROOM', 'Single Room'), ('FLOOR', 'Entire Floor'), ('PHASE', 'Construction Phase'), ('PROJECT', 'Whole Project')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('media_count', models.PositiveIntegerField(default=0)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='timelapses/videos/')),
                ('gif_file', models.FileField(blank=True, null=True, upload_to='timelapses/gifs/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='timelapses/thumbs/')),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('GENERATING', 'Generating'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('NO_MEDIA', 'No Media Found')], default='QUEUED', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('auto_generated', models.BooleanField(default=False, help_text='Was this produced by the weekly/automated pipeline?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timelapses', to='core.floor')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timelapses_generated', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timelapses', to='core.constructionphase')),
                ('project', models.ForeignKey(blank=True, help_text='Which project this timelapse belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timelapses', to='core.houseproject')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timelapses', to='core.room')),
                ('source_media', models.ManyToManyField(blank=True, related_name='timelapses', to='tasks.taskmedia')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Analysis'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped (non-image / unsupported)')], default='PENDING', max_length=20)),
                ('detected_phase_key', models.CharField(blank=True, help_text='One of the PHASE_KEYS constants (FOUNDATION, BRICKWORK, etc.)', max_length=50)),
                ('detected_phase_label', models.CharField(blank=True, max_length=100)),
                ('phase_confidence', models.FloatField(default=0.0, help_text='0.0–1.0 confidence of the detected phase')),
                ('phase_match', models.CharField(choices=[('MATCH', 'Matches Task Phase'), ('MISMATCH', 'Does Not Match Task Phase'), ('INCONCLUSIVE', 'Inconclusive'), ('NO_PHASE', 'Task has no phase')], default='INCONCLUSIVE', max_length=20)),
                ('detected_objects', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list, help_text="Flat list of human-readable tags like 'rebar', 'shuttering', 'brickwork'")),
                ('quality_score', models.FloatField(default=0.0, help_text='0.0–1.0 overall quality (resolution, blur, lighting heuristic)')),
                ('brightness', models.FloatField(default=0.0)),
                ('dominant_colors', models.JSONField(blank=True, default=list)),
                ('analyzer_name', models.CharField(blank=True, help_text='Which analyzer produced this (heuristic, google_vision, openai_vision, …)', max_length=50)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Raw analyzer output for debugging')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='tasks.taskmedia')),
            ],
            options={
                'verbose_name': 'Photo Analysis',
                'verbose_name_plural': 'Photo Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('summary', models.TextField(blank=True, help_text='Human-readable summary')),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('alerts', models.JSONField(blank=True, default=list)),
                ('emailed', models.BooleanField(default=False)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_digests', to='core.houseproject')),
                ('timelapses', models.ManyToManyField(blank=True, related_name='digests', to='photo_intel.timelapse')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('week_start', 'week_end')},
            },
        ),
    ]
