# Generated by Django 4.2.9 on 2026-04-23 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_floor_project'),
        ('photo_intel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelapse',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Which project this timelapse belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timelapses', to='core.houseproject'),
        ),
        migrations.AddField(
            model_name='weeklydigest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_digests', to='core.houseproject'),
        ),
    ]
